Repository yunionio/cloudmux, pull requests merged in 2022-12, with the labels that each got.

#68 fix(hcs): vpc emulated
  pkg/multicloud/hcs/external_vpc.go
Labels: size/XS

#69 Automated cherry pick of #68: fix(hcs): vpc emulated
  pkg/multicloud/hcs/external_vpc.go
Labels: size/XS

#70 fix(hcs): hcs eip addr
  pkg/multicloud/hcs/eip.go
  pkg/multicloud/hcs/shell/eip.go
Labels: size/S

#75 Automated cherry pick of #74: fix(cloudmux):add remotefile host.wire
  pkg/multicloud/remotefile/host.go
Labels: size/XS

#76 add: hcsop const
  pkg/apis/compute/cloudaccount_const.go
Labels: size/XS

#77 Automated cherry pick of #76: add: hcsop const
  pkg/apis/compute/cloudaccount_const.go
Labels: size/XS

#84 fix(cloudmux): fix cloudpods metric
  pkg/multicloud/cloudpods/instance.go
Labels: size/XS

#86 Automated cherry pick of #84: fix(cloudmux): fix cloudpods metric
  pkg/multicloud/cloudpods/instance.go
Labels: size/XS

#91 fix(aws): account read only
  pkg/multicloud/aws/aws.go
Labels: size/XS

#92 Automated cherry pick of #91: fix(aws): account read only
  pkg/multicloud/aws/aws.go
Labels: size/XS

#94 Automated cherry pick of #93: fix(cloudmux): 修改remotefile的getMetric的并发bug
  pkg/multicloud/remotefile/remotefile.go
Labels: size/XS

#96 Automated cherry pick of #95: fix(huawei): huawei rds metric params
  pkg/multicloud/huawei/monitor.go
Labels: size/S

#98 Automated cherry pick of #97: fix(aliyun): redis create params
  pkg/multicloud/aliyun/elasticcache_instance.go
Labels: size/XS

#99 fix(huawei): api request limit
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/huawei/huawei.go
Labels: size/M

#102 fix(cloudmux): modelarts cidr diff
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/XS

#103 Automated cherry pick of #102: fix(cloudmux): modelarts cidr diff
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/XS

#104 fix(openstack): api version
  pkg/multicloud/openstack/openstack.go
Labels: size/XS

#108 fix: update pkg
  .github/workflows/build-and-test.yaml
  go.mod
  go.sum
Labels: size/S

#109 Automated cherry pick of #108: fix: update pkg
  .github/workflows/build-and-test.yaml
  go.mod
  go.sum
Labels: size/S

#110 update go.mod 20221226
  go.mod
  go.sum
Labels: size/XS

#111 Automated cherry pick of #110: update go.mod 20221226
  go.mod
  go.sum
Labels: size/XS

#114 fix(azure): eip sync
  pkg/multicloud/azure/region.go
Labels: size/XS

#116 fix(vmware): add tags sync
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#118 feat(resource tag):sync resource tag
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/elastic_search.go
  pkg/multicloud/aliyun/kafka.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/resource_tags.go
  pkg/multicloud/aliyun/shell/resource_tag.go
  pkg/multicloud/qcloud/elastic_search.go
  pkg/multicloud/qcloud/kafka.go
Labels: size/L

#119 Automated cherry pick of #118 upstream release 3.10
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/elastic_search.go
  pkg/multicloud/aliyun/kafka.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/resource_tags.go
  pkg/multicloud/aliyun/shell/resource_tag.go
  pkg/multicloud/qcloud/elastic_search.go
  pkg/multicloud/qcloud/kafka.go
Labels: size/L

#124 fix: esxi virtualmachine missing datastore property
  pkg/multicloud/esxi/monitor.go
  pkg/multicloud/esxi/shell/monitor.go
  pkg/multicloud/esxi/shell/utils.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#125 Automated cherry pick of #124: fix: esxi virtualmachine missing datastore property
  pkg/multicloud/esxi/monitor.go
  pkg/multicloud/esxi/shell/monitor.go
  pkg/multicloud/esxi/shell/utils.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M
