Repository yunionio/cloudmux, pull requests merged in 2022-11, with the labels that each got.

#4 fix(hcs): obs endpoint
  pkg/multicloud/hcs/hcs.go
Labels: size/XS

#6 fix: aliyun dns record
  pkg/multicloud/aliyun/dns_domain_record.go
Labels: size/S

#5 fix: remove yunion.io/x/onecloud/pkg/cloudcommon/db/lockman
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/M

#7 fix: cloudpods privilege and env check
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/provider/provider.go
Labels: size/S

#8 fix(region): hcso saml provider
  pkg/multicloud/hcso/saml_provider.go
Labels: size/S

#9 fix: remote file eip
  pkg/multicloud/remotefile/eip.go
Labels: size/XS

#10 fix: remove options
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/images.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/saml_provider.go
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/apsara/storagecache.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/saml_provider.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/azure/saml_provider.go
  pkg/multicloud/azure/storagecache.go
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/provider/provider.go
  pkg/multicloud/google/storagecache.go
  pkg/multicloud/hcs/storagecache.go
  pkg/multicloud/hcso/saml_provider.go
  pkg/multicloud/hcso/storagecache.go
  pkg/multicloud/huawei/saml_provider.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/nutanix/storagecache.go
  pkg/multicloud/openstack/storagecache.go
  pkg/multicloud/qcloud/saml_provider.go
  pkg/multicloud/qcloud/storagecache.go
  pkg/multicloud/ucloud/storagecache.go
  pkg/multicloud/zstack/storagecache.go
Labels: size/L

#11 fix: aws options
  pkg/multicloud/aws/instance.go
Labels: size/XS

#12 fix: remove openstack dependency on mcclient
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/document_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-request.md
  .github/pull_request_template.md
  Makefile
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aliyun/shell/monitor.go
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/apsara/storagecache.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/azure/storagecache.go
  pkg/multicloud/bingocloud/storagecache.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/storagecache.go
  pkg/multicloud/ctyun/storagecache.go
  pkg/multicloud/ecloud/storagecache.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/google/storagecache.go
  pkg/multicloud/hcs/storagecache.go
  pkg/multicloud/hcso/storagecache.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/incloudsphere/storagecache.go
  pkg/multicloud/jdcloud/storagecache.go
  pkg/multicloud/nutanix/storagecache.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/oscli/catalog.go
  pkg/multicloud/openstack/oscli/input.go
  pkg/multicloud/openstack/oscli/oscli.go
  pkg/multicloud/openstack/oscli/session.go
  pkg/multicloud/openstack/oscli/token.go
  pkg/multicloud/openstack/oscli/token2.go
  pkg/multicloud/openstack/oscli/token3.go
  pkg/multicloud/openstack/oscli/tokensimple.go
  pkg/multicloud/openstack/project.go
  pkg/multicloud/openstack/storagecache.go
  pkg/multicloud/proxmox/storagecache.go
  pkg/multicloud/qcloud/storagecache.go
  pkg/multicloud/ucloud/storagecache.go
  pkg/multicloud/zstack/storagecache.go
Labels: size/XXL

#13 fix: update README
  README.md
Labels: size/XS

#15 fix(cloudmux): modelarts refresh
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/XS, lgtm

#17 fix: remove dependency
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/errors.go
  pkg/cloudprovider/i18n.go
  pkg/cloudprovider/objectstore.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aliyun/shell/monitor.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/provider/provider.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/ecloud/monitor.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/ecloud/request.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/hcs/provider/provider.go
  pkg/multicloud/hcso/client/modules/manager_base.go
  pkg/multicloud/hcso/client/modules/mod_ces.go
  pkg/multicloud/hcso/client/modules/mod_images.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/client/modules/mod_ces.go
  pkg/multicloud/huawei/client/modules/mod_images.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/incloudsphere/provider/provider.go
  pkg/multicloud/jdcloud/image.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/objectstore/ceph/adminapi.go
  pkg/multicloud/objectstore/ceph/bucket.go
  pkg/multicloud/objectstore/ceph/ceph.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/objectstore/xsky/adminapi.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/oscli/session.go
  pkg/multicloud/openstack/oscli/token3.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/proxmox/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/remotefile/provider/provider.go
  pkg/multicloud/ucloud/client.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: size/XL

#18 fix: geo equals
  pkg/cloudprovider/geoinfo.go
Labels: size/XS

#19 fix: qcloud 2.0 -> 3.0 api migrate
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/natdtable.go
  pkg/multicloud/qcloud/natgateway.go
  pkg/multicloud/qcloud/project.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/natdtable.go
  pkg/multicloud/qcloud/shell/project.go
  pkg/multicloud/qcloud/shell/vpc.go
  pkg/multicloud/qcloud/tags.go
  pkg/multicloud/qcloud/vpc.go
  pkg/multicloud/qcloud/vpc_peering_connection.go
Labels: size/XXL

#20 fix(cloudmux): remoteFile metric
  pkg/multicloud/remotefile/monitor.go
  pkg/multicloud/remotefile/remotefile.go
Labels: size/S, lgtm

#21 fix(region): hcso region cache
  pkg/multicloud/hcso/huawei.go
Labels: size/S

#22 fix(cloudmux):add guest power status
  pkg/apis/compute/guest_const.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/hcs/instance.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/instance_base.go
Labels: size/M

#23 fix:modelarts status
  pkg/apis/compute/modelarts_pool.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/S

#24 fix: do not probe esxi vm ip address
  pkg/multicloud/esxi/net_topology.go
  pkg/multicloud/esxi/net_topology_pro.go
Labels: size/M

#25 fix(cloudmux): add modelarts created failed
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#26 fix(cloudmux): fix modelarts network no available bug
  pkg/cloudprovider/modelarts_pool.go
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#28 fix(region): hcs misc fix
  pkg/multicloud/hcs/hcs.go
  pkg/multicloud/hcs/instance.go
  pkg/multicloud/hcs/port.go
  pkg/multicloud/hcs/shell/port.go
  pkg/multicloud/hcs/shell/securitygroup.go
Labels: size/M

#27 fix(cloudmux): add modelarts sku processor_type
  pkg/apis/compute/modelarts_pool_sku.go
  pkg/multicloud/hcso/modelarts_sku.go
  pkg/multicloud/huawei/modelarts_pool_sku.go
Labels: size/S

#31 fix(region): hcs bucket
  pkg/multicloud/hcs/bucket.go
  pkg/multicloud/hcs/region.go
Labels: size/S

#32 fix: cloudpods self manage check
  pkg/multicloud/cloudpods/cloudpods.go
Labels: size/XS

#33 fix: hcs vm create
  pkg/multicloud/hcs/host.go
Labels: size/XS

#34 fix(hcs): dnat create
  pkg/multicloud/hcs/natdtable.go
  pkg/multicloud/hcs/port.go
Labels: size/S

#30 fix(cloudmux): fix modelarts sku glableId
  pkg/multicloud/hcso/modelarts_sku.go
  pkg/multicloud/huawei/modelarts_pool_sku.go
Labels: size/S, lgtm

#35 fix: lb refactor
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/loadbalancer.go
  pkg/multicloud/aliyun/loadbalancerhttplistener.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aliyun/loadbalancertcplistener.go
  pkg/multicloud/aliyun/loadbalancerudplistener.go
  pkg/multicloud/apsara/loadbalancer.go
  pkg/multicloud/apsara/loadbalancerhttplistener.go
  pkg/multicloud/apsara/loadbalancerhttpslistener.go
  pkg/multicloud/apsara/loadbalancertcplistener.go
  pkg/multicloud/apsara/loadbalancerudplistener.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancerlistener.go
  pkg/multicloud/google/loadbalancer.go
  pkg/multicloud/google/loadbalancer_listener.go
  pkg/multicloud/hcs/loadbalancer.go
  pkg/multicloud/hcs/loadbalancer_listener.go
  pkg/multicloud/hcso/loadbalancer.go
  pkg/multicloud/hcso/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/shell/loadbalancer.go
  pkg/multicloud/openstack/loadbalancerl7policy.go
  pkg/multicloud/openstack/loadbalancerlistener.go
  pkg/multicloud/openstack/loadbalbacer.go
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_acl.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/remotefile/loadbalancer.go
Labels: size/XXL

#36 fix: huawei aws lb
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/hcs/loadbalancer.go
  pkg/multicloud/hcs/shell/lb.go
  pkg/multicloud/hcso/loadbalancer.go
  pkg/multicloud/hcso/shell/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/shell/loadbalancer.go
Labels: size/M

#37 fix(cloudmux): fix modelarts network status
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/S

#38 fix(cloudmux): add cloudprovider.GetProcessorType
  pkg/cloudprovider/cloudprovider.go
Labels: size/XS

#39 fix: hcs vm attach
  pkg/multicloud/hcs/disk.go
Labels: size/XS

#41 fix: huawei elb backendgroup
  pkg/cloudprovider/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/hcs/loadbalancer.go
  pkg/multicloud/hcs/loadbalancer_backendgroup.go
  pkg/multicloud/hcs/loadbalancer_listener.go
  pkg/multicloud/hcs/shell/lb.go
  pkg/multicloud/hcso/loadbalancer.go
  pkg/multicloud/hcso/loadbalancer_backendgroup.go
  pkg/multicloud/hcso/loadbalancer_listener.go
  pkg/multicloud/hcso/shell/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/shell/loadbalancer.go
  pkg/multicloud/openstack/loadbalabcerpool.go
  pkg/multicloud/openstack/loadbalbacer.go
Labels: size/XXL

#42 fix: hcs misc
  pkg/multicloud/hcs/disk.go
  pkg/multicloud/hcs/eip.go
  pkg/multicloud/hcs/hcs.go
  pkg/multicloud/hcs/instance.go
  pkg/multicloud/hcs/job.go
  pkg/multicloud/hcs/redis.go
  pkg/multicloud/hcso/elasticcache_instance.go
  scripts/cherry_pick_pull.sh
Labels: size/M

#46 fix(region): hcs redis create
  pkg/multicloud/hcs/redis.go
Labels: size/XS

#52 fix: hcso http retry
  pkg/multicloud/hcso/client/modules/manager_base.go
Labels: size/M

#53 Automated cherry pick of #52: fix: hcso http retry
  pkg/multicloud/hcso/client/modules/manager_base.go
Labels: size/M

#54 fix(cloudmux): add remotefile guest power status
  pkg/cloudprovider/resources.go
  pkg/multicloud/remotefile/instance.go
Labels: size/XS

#57 fix(cloudpods): vm vnc shell
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/cloudpods/shell/instance.go
Labels: size/S

#59 Automated cherry pick of #58: fix: aws instance os_arch
  pkg/multicloud/aws/instance.go
Labels: size/S

#60 fix(hcs): vpc peer
  pkg/apis/compute/network_const.go
  pkg/multicloud/hcs/eip.go
  pkg/multicloud/hcs/external_network.go
  pkg/multicloud/hcs/external_vpc.go
  pkg/multicloud/hcs/external_wire.go
  pkg/multicloud/hcs/hcs.go
  pkg/multicloud/hcs/region.go
  pkg/multicloud/hcs/shell/eip.go
  pkg/multicloud/hcs/shell/network.go
  pkg/multicloud/hcs/shell/vpc.go
  pkg/multicloud/hcs/shell/vpc_peer.go
  pkg/multicloud/hcs/vpc.go
  pkg/multicloud/hcs/vpc_peering.go
Labels: size/XL

#61 Automated cherry pick of #60: fix(hcs): vpc peer
  pkg/apis/compute/network_const.go
  pkg/multicloud/hcs/eip.go
  pkg/multicloud/hcs/external_network.go
  pkg/multicloud/hcs/external_vpc.go
  pkg/multicloud/hcs/external_wire.go
  pkg/multicloud/hcs/hcs.go
  pkg/multicloud/hcs/region.go
  pkg/multicloud/hcs/shell/eip.go
  pkg/multicloud/hcs/shell/network.go
  pkg/multicloud/hcs/shell/vpc.go
  pkg/multicloud/hcs/shell/vpc_peer.go
  pkg/multicloud/hcs/vpc.go
  pkg/multicloud/hcs/vpc_peering.go
Labels: size/XL

#62 fix(hcs); peer shell
  pkg/multicloud/hcs/shell/vpc_peer.go
Labels: size/S

#63 Automated cherry pick of #62: fix(hcs); peer shell
  pkg/multicloud/hcs/shell/vpc_peer.go
Labels: size/S

#64 fix(hcs): metric
  cmd/hcscli/main.go
  pkg/multicloud/hcs/hcs.go
  pkg/multicloud/hcs/monitor.go
  pkg/multicloud/hcs/provider/provider.go
  pkg/multicloud/hcso/client/auth/signer.go
Labels: size/XL

#66 fix(hcs): remove debug log
  pkg/multicloud/hcs/monitor.go
Labels: size/XS
