Repository yunionio/cloudmux, pull requests merged in 2022-10, with the labels that each got.

#2 fix: hcs vpc and vnc
  pkg/multicloud/hcs/hcs.go
  pkg/multicloud/hcs/instance.go
  pkg/multicloud/hcs/shell/instance.go
  pkg/multicloud/hcs/vpc.go
  pkg/multicloud/hcs/wire.go
Labels: size/M

#1 fix: remove unused consts
  .gitignore
  go.mod
  go.sum
  pkg/apis/cloudid/cloudid.go
  pkg/apis/cloudid/cloudpolicy.go
  pkg/apis/cloudid/saml_provider.go
  pkg/apis/compute/bucket.go
  pkg/apis/compute/cachedimages_const.go
  pkg/apis/compute/cdn.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/dbinstance_const.go
  pkg/apis/compute/disk_const.go
  pkg/apis/compute/dnszone.go
  pkg/apis/compute/elastic_search.go
  pkg/apis/compute/elasticache_const.go
  pkg/apis/compute/elasticips_const.go
  pkg/apis/compute/externalproject.go
  pkg/apis/compute/filesystem.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/inter_vpc_network.go
  pkg/apis/compute/kafka.go
  pkg/apis/compute/kube_cluster.go
  pkg/apis/compute/loadbalancer_const.go
  pkg/apis/compute/modelarts_pool.go
  pkg/apis/compute/mongodb_const.go
  pkg/apis/compute/mount_targets.go
  pkg/apis/compute/natgateway.go
  pkg/apis/compute/network_const.go
  pkg/apis/compute/networkinterface_const.go
  pkg/apis/compute/routetable.go
  pkg/apis/compute/secgroup_const.go
  pkg/apis/compute/sku_const.go
  pkg/apis/compute/snapshot_const.go
  pkg/apis/compute/storage_const.go
  pkg/apis/compute/vpc_peering_connection.go
  pkg/apis/compute/vpcs_const.go
  pkg/apis/compute/vpcs_ovn.go
  pkg/apis/compute/waf_instance.go
  pkg/apis/compute/wire_const.go
  pkg/apis/compute/zones_const.go
  pkg/apis/const.go
  pkg/apis/share.go
Labels: size/XXL

#3 fix: lb interface
  pkg/cloudprovider/fakeregion.go
  pkg/cloudprovider/loadbalancer.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/hcs/loadbalancer.go
  pkg/multicloud/hcs/shell/lb.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/hcso/shell/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/loadbalancer.go
  pkg/multicloud/no_lb_region.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/openstack/loadbalbacer.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/region_base.go
  pkg/multicloud/remotefile/region.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/zstack/region.go
Labels: size/L
