Repository yunionio/cloudmux, pull requests merged in 2023-09, with the labels that each got.

#420 fix: esxi vm nics should consider exists even if no ip
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/XS

#421 fix(aws): support gp3 throughput
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/shell/disk.go
Labels: size/M

#422 fix(aws): bucket forbidden
  pkg/multicloud/aws/aws.go
Labels: size/XS

#423 Automated cherry pick of #422: fix(aws): bucket forbidden
  pkg/multicloud/aws/aws.go
Labels: size/XS

#428 fix(openstack): set vm tags
  pkg/multicloud/openstack/instance.go
Labels: size/M

#424 feat(all): support ecs,rds description
  pkg/cloudprovider/dbinstance.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/shell/dbinstance.go
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/apsara/shell/instance.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/eks.go
  pkg/multicloud/aws/eks_node_group.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/internetgateway.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackend.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancercert.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/routetable.go
  pkg/multicloud/aws/saml_provider.go
  pkg/multicloud/aws/shell/instance.go
  pkg/multicloud/aws/snapshot.go
  pkg/multicloud/aws/storage.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/aws/tag_base.go
  pkg/multicloud/aws/vpc_peering_connection.go
  pkg/multicloud/aws/waf.go
  pkg/multicloud/aws/wire.go
  pkg/multicloud/aws/zone.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/dbinstance_base.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/hcso/shell/instance.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/shell/dbinstance.go
  pkg/multicloud/huawei/shell/instance.go
  pkg/multicloud/jdcloud/instance.go
  pkg/multicloud/nutanix/instance.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/proxmox/instance.go
  pkg/multicloud/qcloud/dbinstance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/rds_mysql.go
  pkg/multicloud/remotefile/dbinstance.go
  pkg/multicloud/remotefile/instance.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/instance.go
Labels: size/L

#431 fix(google): skip invalid google project
  pkg/multicloud/google/google.go
Labels: size/XS

#433 fix(aliyun,aws):Support resource desc
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/shell/dbinstance.go
Labels: size/M

#434 fix(google): skip google invalid rule
  pkg/multicloud/google/securitygroup.go
Labels: size/XS

#435 Automated cherry pick of #434: fix(google): skip google invalid rule
  pkg/multicloud/google/securitygroup.go
Labels: size/XS

#436 fix(qcloud): fix empty zone
  pkg/multicloud/qcloud/qcloud.go
Labels: size/XS

#438 Automated cherry pick of #436: fix(qcloud): fix empty zone
  pkg/multicloud/qcloud/qcloud.go
Labels: size/XS

#439 fix(huawei): enterprise project
  pkg/multicloud/huawei/enterpriseprojects.go
Labels: size/XS

#440 Automated cherry pick of #439: fix(huawei): enterprise project
  pkg/multicloud/huawei/enterpriseprojects.go
Labels: size/XS

#443 Automated cherry pick of #442: fix(aws): storage emulated
  pkg/multicloud/aws/storage.go
Labels: size/XS

#445 fix(region): skip invalid project
  pkg/multicloud/huawei/huawei.go
Labels: size/S

#446 Automated cherry pick of #445: fix(region): skip invalid project
  pkg/multicloud/huawei/huawei.go
Labels: size/S

#447 Automated cherry pick of #445: fix(region): skip invalid project
  pkg/multicloud/huawei/huawei.go
Labels: size/S

#448 fix(esxi): linux hostname
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/S

#449 Automated cherry pick of #448: fix(esxi): linux hostname
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/S

#450 Automated cherry pick of #448: fix(esxi): linux hostname
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/S

#451 fix(aws): disk type
  pkg/multicloud/aws/disk.go
Labels: size/XS

#452 Automated cherry pick of #451: fix(aws): disk type
  pkg/multicloud/aws/disk.go
Labels: size/XS

#454 fix(vmware): remove clone template old nic
  pkg/multicloud/esxi/host.go
Labels: size/L

#455 Automated cherry pick of #454: fix(vmware): remove clone template old nic
  pkg/multicloud/esxi/host.go
Labels: size/L

#456 Automated cherry pick of #454: fix(vmware): remove clone template old nic
  pkg/multicloud/esxi/host.go
Labels: size/L
