Repository yunionio/cloudmux, pull requests merged in 2023-02, with the labels that each got.

#168 feat(bingocloud)：implemented some instance interfaces
  pkg/cloudprovider/errors.go
  pkg/cloudprovider/securitygroup.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/cluster.go
  pkg/multicloud/bingocloud/disk.go
  pkg/multicloud/bingocloud/eip.go
  pkg/multicloud/bingocloud/host.go
  pkg/multicloud/bingocloud/image.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/bingocloud/instance_snapshot.go
  pkg/multicloud/bingocloud/instance_type.go
  pkg/multicloud/bingocloud/instancenic.go
  pkg/multicloud/bingocloud/monitor.go
  pkg/multicloud/bingocloud/network.go
  pkg/multicloud/bingocloud/node.go
  pkg/multicloud/bingocloud/region.go
  pkg/multicloud/bingocloud/securitygroup.go
  pkg/multicloud/bingocloud/snapshot.go
  pkg/multicloud/bingocloud/storage.go
  pkg/multicloud/bingocloud/utils.go
  pkg/multicloud/bingocloud/vpc.go
  pkg/multicloud/bingocloud/wire.go
  pkg/multicloud/bingocloud/zone.go
Labels: size/XXL

#170 Automated cherry pick of #168: feat(bingocloud)：implemented some instance interfaces
  pkg/cloudprovider/errors.go
  pkg/cloudprovider/securitygroup.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/cluster.go
  pkg/multicloud/bingocloud/disk.go
  pkg/multicloud/bingocloud/eip.go
  pkg/multicloud/bingocloud/host.go
  pkg/multicloud/bingocloud/image.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/bingocloud/instance_snapshot.go
  pkg/multicloud/bingocloud/instance_type.go
  pkg/multicloud/bingocloud/instancenic.go
  pkg/multicloud/bingocloud/monitor.go
  pkg/multicloud/bingocloud/network.go
  pkg/multicloud/bingocloud/node.go
  pkg/multicloud/bingocloud/region.go
  pkg/multicloud/bingocloud/securitygroup.go
  pkg/multicloud/bingocloud/snapshot.go
  pkg/multicloud/bingocloud/storage.go
  pkg/multicloud/bingocloud/utils.go
  pkg/multicloud/bingocloud/vpc.go
  pkg/multicloud/bingocloud/wire.go
  pkg/multicloud/bingocloud/zone.go
Labels: size/XXL

#171 fix(qcloud): cdn attr sync
  pkg/cloudprovider/cdn.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/cdn.go
  pkg/multicloud/cdn_domain_base.go
  pkg/multicloud/qcloud/cdn.go
Labels: size/XL

#172 Automated cherry pick of #171: fix(qcloud): cdn attr sync
  pkg/cloudprovider/cdn.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/cdn.go
  pkg/multicloud/cdn_domain_base.go
  pkg/multicloud/qcloud/cdn.go
Labels: size/XL

#173 fix(qcloud): cdn project id
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/cdn.go
  pkg/multicloud/qcloud/cdn.go
Labels: size/S

#175 fix(huawei): metric skip read only check
  pkg/multicloud/huawei/huawei.go
Labels: size/XS

#181 fix(google): gcp storage cache
  pkg/multicloud/google/storagecache.go
Labels: size/XS

#182 Automated cherry pick of #181: fix(google): gcp storage cache
  pkg/multicloud/google/storagecache.go
Labels: size/XS

#183 fix(google): gcp storage cache
  pkg/multicloud/google/storagecache.go
Labels: size/XS

#184 Automated cherry pick of #183: fix(google): gcp storage cache
  pkg/multicloud/google/storagecache.go
Labels: size/XS

#185 fix(gcp): google storage id
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/google/latitude_and_longitude.go
  pkg/multicloud/google/storage.go
Labels: size/M

#190 Automated cherry pick of #189: fix(aliyun): lb tags
  pkg/multicloud/aliyun/loadbalancer.go
Labels: size/XS
