Repository yunionio/cloudmux, pull requests merged in 2023-08, with the labels that each got.

#364 fix: apsara bucket list
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/azure/azure.go
Labels: size/M

#365 Automated cherry pick of #364: fix: apsara bucket list
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/azure/azure.go
Labels: size/M

#368 Automated cherry pick of #367: fix: get_balance return params error
  pkg/multicloud/cmx/shell/balance.go
Labels: size/XS

#367 fix: get_balance return params error
  pkg/multicloud/cmx/shell/balance.go
Labels: size/XS

#366 fix: inic add vlanId method
  pkg/apis/compute/host_const.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/esxi/hostnic.go
Labels: size/S

#371 fix(ksyun): add region code
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/loader/loader.go
Labels: size/XL

#372 feat(baidu): support baidu
  cmd/baiducli/main.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/baidu/baidu.go
  pkg/multicloud/baidu/baiducli/main.go
  pkg/multicloud/baidu/provider/provider.go
  pkg/multicloud/baidu/region.go
  pkg/multicloud/baidu/shell/balance.go
  pkg/multicloud/baidu/shell/printutil.go
  pkg/multicloud/baidu/shell/region.go
  pkg/multicloud/baidu/signer.go
  pkg/multicloud/ctyun/latitud_and_longitude.go
  pkg/multicloud/ecloud/latitud_and_longitude.go
  pkg/multicloud/loader/loader.go
Labels: size/XXL

#373 fix(cucloud): add china union cloud
  cmd/cucli/main.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/multicloud/cucloud/cucli/main.go
  pkg/multicloud/cucloud/cucloud.go
  pkg/multicloud/cucloud/provider/provider.go
  pkg/multicloud/cucloud/region.go
  pkg/multicloud/cucloud/shell/balance.go
  pkg/multicloud/cucloud/shell/printutil.go
  pkg/multicloud/cucloud/shell/region.go
  pkg/multicloud/loader/loader.go
Labels: size/XL

#376 feat: support qingcloud
  cmd/qingcli/main.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/multicloud/loader/loader.go
  pkg/multicloud/qingcloud/provider/provider.go
  pkg/multicloud/qingcloud/qingcli/main.go
  pkg/multicloud/qingcloud/qingcloud.go
  pkg/multicloud/qingcloud/region.go
  pkg/multicloud/qingcloud/shell/printutil.go
  pkg/multicloud/qingcloud/shell/region.go
  pkg/multicloud/qingcloud/shell/zone.go
  pkg/multicloud/qingcloud/zone.go
Labels: size/XL

#377 fix: update docker yml
  .github/workflows/docker_build_push.yml
Labels: size/XS

#378 Automated cherry pick of #377: fix: update docker yml
  .github/workflows/docker_build_push.yml
Labels: size/M

#379 fix: docker username
  .github/workflows/docker_build_push.yml
Labels: size/XS

#380 Automated cherry pick of #379: fix: docker username
  .github/workflows/docker_build_push.yml
Labels: size/XS

#383 fix: workflow secret
  .github/workflows/docker_build_push.yml
Labels: size/S

#385 fix: tls timeout
  .github/workflows/docker_build_push.yml
Labels: size/XS

#389 fix(aws): tags
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/natgateway.go
  pkg/multicloud/aws/resource_tag.go
  pkg/multicloud/aws/shell/lb.go
  pkg/multicloud/aws/shell/resource_tag.go
  pkg/multicloud/aws/utils.go
Labels: size/L

#390 Automated cherry pick of #389: fix(aws): tags
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/natgateway.go
  pkg/multicloud/aws/resource_tag.go
  pkg/multicloud/aws/shell/lb.go
  pkg/multicloud/aws/shell/resource_tag.go
  pkg/multicloud/aws/utils.go
Labels: size/L

#391 fix: aws eip retry
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/eip.go
Labels: size/M

#393 fix: eip tags
  pkg/cloudprovider/eip.go
  pkg/multicloud/aliyun/eip.go
  pkg/multicloud/aliyun/shell/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/eip.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/qcloud/eip.go
  pkg/multicloud/qcloud/shell/eip.go
  pkg/multicloud/zstack/region.go
Labels: size/L

#394 Automated cherry pick of #393: fix: eip tags
  pkg/cloudprovider/eip.go
  pkg/multicloud/aliyun/eip.go
  pkg/multicloud/aliyun/shell/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/eip.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/qcloud/eip.go
  pkg/multicloud/qcloud/shell/eip.go
  pkg/multicloud/zstack/region.go
Labels: size/L

#395 fix(qcloud): skip disabled project
  pkg/multicloud/qcloud/project.go
Labels: size/XS

#396 Automated cherry pick of #395: fix(qcloud): skip disabled project
  pkg/multicloud/qcloud/project.go
Labels: size/XS

#397 fix: replace hostwires with hostnetifs
  pkg/cloudprovider/hostnetifs.go
  pkg/cloudprovider/hostnetifs_test.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/apsara/host.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/azure/classic_host.go
  pkg/multicloud/azure/host.go
  pkg/multicloud/bingocloud/node.go
  pkg/multicloud/ctyun/host.go
  pkg/multicloud/ecloud/host.go
  pkg/multicloud/esxi/compact_ips.go
  pkg/multicloud/esxi/compact_ips_test.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/fakeregion.go
  pkg/multicloud/esxi/fakevpc.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/hostnic.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/mobase.go
  pkg/multicloud/esxi/net_topology_pro.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/shell/host.go
  pkg/multicloud/esxi/shell/network.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/tags.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/esxi/wire.go
  pkg/multicloud/google/host.go
  pkg/multicloud/hcso/host.go
  pkg/multicloud/huawei/host.go
  pkg/multicloud/jdcloud/host.go
  pkg/multicloud/nutanix/host.go
  pkg/multicloud/openstack/hypervisor.go
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/remotefile/host.go
  pkg/multicloud/ucloud/host.go
  pkg/multicloud/zstack/host.go
Labels: size/XXL

#399 Automated cherry pick of #398: fix: tencent cloud storage
  pkg/multicloud/qcloud/zone.go
Labels: size/XS

#400 fix: dns zone refactor
  pkg/cloudprovider/dnszone.go
  pkg/cloudprovider/dnszone_test.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/dns_domain.go
  pkg/multicloud/aliyun/dns_domain_record.go
  pkg/multicloud/aliyun/private_zone.go
  pkg/multicloud/aliyun/private_zone_record.go
  pkg/multicloud/aliyun/shell/dns_domain.go
  pkg/multicloud/aliyun/shell/private_zone.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/aws_xml_request.go
  pkg/multicloud/aws/dnshostedzone.go
  pkg/multicloud/aws/dnsrecord.go
  pkg/multicloud/aws/dnsrecordset.go
  pkg/multicloud/aws/dnstrafficpolicy.go
  pkg/multicloud/aws/dnszone.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/dnszone.go
  pkg/multicloud/qcloud/dnspod_domain.go
  pkg/multicloud/qcloud/dnspod_record.go
  pkg/multicloud/qcloud/shell/dnspod.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/route53/doc.go
  vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
  vendor/github.com/aws/aws-sdk-go/service/route53/service.go
  vendor/github.com/aws/aws-sdk-go/service/route53/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/service/route53/waiters.go
  vendor/modules.txt
Labels: size/XXL

#402 Automated cherry pick of #400: fix: dns zone refactor
  pkg/cloudprovider/dnszone.go
  pkg/cloudprovider/dnszone_test.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/dns_domain.go
  pkg/multicloud/aliyun/dns_domain_record.go
  pkg/multicloud/aliyun/private_zone.go
  pkg/multicloud/aliyun/private_zone_record.go
  pkg/multicloud/aliyun/shell/dns_domain.go
  pkg/multicloud/aliyun/shell/private_zone.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/aws_xml_request.go
  pkg/multicloud/aws/dnshostedzone.go
  pkg/multicloud/aws/dnsrecord.go
  pkg/multicloud/aws/dnsrecordset.go
  pkg/multicloud/aws/dnstrafficpolicy.go
  pkg/multicloud/aws/dnszone.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/dnszone.go
  pkg/multicloud/qcloud/dnspod_domain.go
  pkg/multicloud/qcloud/dnspod_record.go
  pkg/multicloud/qcloud/shell/dnspod.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/route53/doc.go
  vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
  vendor/github.com/aws/aws-sdk-go/service/route53/service.go
  vendor/github.com/aws/aws-sdk-go/service/route53/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/service/route53/waiters.go
  vendor/modules.txt
Labels: size/XXL

#403 fix: esxi log
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#404 Automated cherry pick of #403: fix: esxi log
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#405 fix: aws system tags
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/shell/lb.go
  pkg/multicloud/aws/tag_base.go
Labels: size/M

#407 fix(esxi): vmware name and tag sync
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/L

#408 Automated cherry pick of #407: fix(esxi): vmware name and tag sync
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/L

#411 fix: vmware wire id should be scoped by cloud account
  pkg/multicloud/esxi/wire.go
Labels: size/XS
