Repository yunionio/cloudmux, pull requests merged in 2023-01, with the labels that each got.

#132 fix(aws): optimized lb
  pkg/apis/compute/loadbalancer_const.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackend.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/backendgroup.go
  pkg/multicloud/aws/shell/lb.go
  pkg/multicloud/aws/shell/listener.go
Labels: size/XXL

#131 Automated cherry pick of #130: fix(aliyun): system disk storage type
  pkg/multicloud/aliyun/zone.go
Labels: size/S

#134 fix(common): default host cpu arch is x86_64
  pkg/multicloud/host_base.go
Labels: size/XS

#139 fix(qcloud): skip unsupport memcache
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/elasticcache.go
Labels: size/S

#142 Automated cherry pick of #141: feat(bingocloud)：implemented some instance interfaces
  pkg/multicloud/bingocloud/instance.go
Labels: size/M

#143 fix(aliyun): vnc os name
  pkg/multicloud/aliyun/instance.go
Labels: size/XS

#144 Automated cherry pick of #143: fix(aliyun): vnc os name
  pkg/multicloud/aliyun/instance.go
Labels: size/XS

#145 fix(vmware): vm migrate
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#154 fix(openstack): vm refresh
  pkg/multicloud/openstack/instance.go
Labels: size/XS

#157 Automated cherry pick of #156: fix(qcloud): qcloud lb listener
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
  pkg/multicloud/qcloud/shell/loadbalancer.go
Labels: size/L

#159 Automated cherry pick of #158: fix(esxi): timeout
  pkg/multicloud/esxi/manager.go
Labels: size/S

#160 fix(esxi): rebuild root
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#162 fix(huawei): clirc region
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
Labels: size/S

#163 Automated cherry pick of #162: fix(huawei): clirc region
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
Labels: size/S

#164 fix(aliyun): aliyun shared image sync
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/aliyun/storagecache.go
Labels: size/S

#167 Automated cherry pick of #166: fix: lb listener update
  pkg/cloudprovider/fakeregion.go
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/loadbalanceracl.go
  pkg/multicloud/aliyun/loadbalancerhttplistener.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aliyun/loadbalancertcplistener.go
  pkg/multicloud/aliyun/loadbalancerudplistener.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/apsara/loadbalancerhttplistener.go
  pkg/multicloud/apsara/loadbalancerhttpslistener.go
  pkg/multicloud/apsara/loadbalancertcplistener.go
  pkg/multicloud/apsara/loadbalancerudplistener.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancerlistener.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/esxi/fakeregion.go
  pkg/multicloud/google/loadbalancer_listener.go
  pkg/multicloud/hcs/loadbalancer_listener.go
  pkg/multicloud/hcso/loadbalancer_listener.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/no_lb_region.go
  pkg/multicloud/openstack/loadbalancerlistener.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/shell/loadbalancer.go
  pkg/multicloud/region_base.go
Labels: size/XXL
