Repository yunionio/cloudmux, pull requests merged in 2023-11, with the labels that each got.

#521 fix: fix GetBucketPolicyErr
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/huawei/bucket.go
Labels: size/L

#525 Automated cherry pick of #521: fix: fix GetBucketPolicyErr
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/huawei/bucket.go
Labels: size/L

#530 fix(volc): bucket opts
  pkg/multicloud/volcengine/bucket.go
  pkg/multicloud/volcengine/objects.go
  pkg/multicloud/volcengine/provider/provider.go
Labels: size/L

#532 fix: volc private image
  pkg/multicloud/volcengine/image.go
  pkg/multicloud/volcengine/shell/image.go
  pkg/multicloud/volcengine/storagecache.go
Labels: size/L

#533 Automated cherry pick of #532: fix: volc private image
  pkg/multicloud/volcengine/image.go
  pkg/multicloud/volcengine/shell/image.go
  pkg/multicloud/volcengine/storagecache.go
Labels: size/L

#535 Automated cherry pick of #534: fix(huawei): lb project
  pkg/multicloud/huawei/loadbalancer.go
Labels: size/M

#536 Automated cherry pick of #534: fix(huawei): lb project
  pkg/multicloud/huawei/loadbalancer.go
Labels: size/M

#539 fix: volc metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/volcengine/monitor.go
  pkg/multicloud/volcengine/network.go
  pkg/multicloud/volcengine/provider/provider.go
  pkg/multicloud/volcengine/shell/monitor.go
  pkg/multicloud/volcengine/volcengine.go
Labels: size/L

#540 Automated cherry pick of #539: fix: volc metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/volcengine/monitor.go
  pkg/multicloud/volcengine/network.go
  pkg/multicloud/volcengine/provider/provider.go
  pkg/multicloud/volcengine/shell/monitor.go
  pkg/multicloud/volcengine/volcengine.go
Labels: size/L

#541 feat(region): qcloud&aliyun&huawei add sslcertificate resource sync
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/sslcertificate.go
  pkg/multicloud/aliyun/sslcertificate.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/shell/sslcertificate.go
  pkg/multicloud/huawei/sslcertificate.go
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/shell/certificate.go
  pkg/multicloud/region_base.go
Labels: size/XL

#543 Automated cherry pick of #541: feat(region): qcloud&aliyun&huawei add sslcertificate resource sync
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/sslcertificate.go
  pkg/multicloud/aliyun/sslcertificate.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/shell/sslcertificate.go
  pkg/multicloud/huawei/sslcertificate.go
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/shell/certificate.go
  pkg/multicloud/region_base.go
Labels: size/XL

#542 fix: fetch subaccounts with id
  cmd/cmx/shell/balance.go
  cmd/cmx/shell/cloudprovider.go
  cmd/cmx/shell/cmd.go
  cmd/cmx/shell/eip.go
  cmd/cmx/shell/helper.go
  cmd/cmx/shell/host.go
  cmd/cmx/shell/instance.go
  cmd/cmx/shell/objectstore.go
  cmd/cmx/shell/options.go
  cmd/cmx/shell/vpc.go
  cmd/cmx/shell/zone.go
  pkg/cloudprovider/subaccount.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/aws/organizations.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/baidu/baidu.go
  pkg/multicloud/cmx/main.go
  pkg/multicloud/cmx/shell/balance.go
  pkg/multicloud/cmx/shell/cloudprovider.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/cucloud/cucloud.go
  pkg/multicloud/ecloud/client.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/shell/account.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/jdcloud/jdcloud.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qingcloud/qingcloud.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/volcengine/provider/provider.go
  pkg/multicloud/volcengine/volcengine.go
Labels: size/XXL

#544 Automated cherry pick of #542: fix: fetch subaccounts with id
  cmd/cmx/shell/balance.go
  cmd/cmx/shell/cloudprovider.go
  cmd/cmx/shell/cmd.go
  cmd/cmx/shell/eip.go
  cmd/cmx/shell/helper.go
  cmd/cmx/shell/host.go
  cmd/cmx/shell/instance.go
  cmd/cmx/shell/objectstore.go
  cmd/cmx/shell/options.go
  cmd/cmx/shell/vpc.go
  cmd/cmx/shell/zone.go
  pkg/cloudprovider/subaccount.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/aws/organizations.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/baidu/baidu.go
  pkg/multicloud/cmx/main.go
  pkg/multicloud/cmx/shell/balance.go
  pkg/multicloud/cmx/shell/cloudprovider.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/cucloud/cucloud.go
  pkg/multicloud/ecloud/client.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/shell/account.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/jdcloud/jdcloud.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qingcloud/qingcloud.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/volcengine/provider/provider.go
  pkg/multicloud/volcengine/volcengine.go
Labels: size/XXL

#545 fix(pve): min vm id
  pkg/multicloud/proxmox/cluster.go
Labels: size/XS

#546 Automated cherry pick of #545: fix(pve): min vm id
  pkg/multicloud/proxmox/cluster.go
Labels: size/XS

#547 Automated cherry pick of #545: fix(pve): min vm id
  pkg/multicloud/proxmox/cluster.go
Labels: size/XS

#548 fix(pve): search pve vm with timeout
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#549 Automated cherry pick of #548: fix(pve): search pve vm with timeout
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#550 Automated cherry pick of #548: fix(pve): search pve vm with timeout
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#551 fix(pve): vnc
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#554 fix(pve): vnc
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#555 Automated cherry pick of #554: fix(pve): vnc
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#556 Automated cherry pick of #554: fix(pve): vnc
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#558 fix(aliyun): avoid panic when get redis cache mod
  pkg/multicloud/aliyun/elasticcache_instance.go
Labels: size/XS

#559 Automated cherry pick of #558: fix(aliyun): avoid panic when get redis cache mod
  pkg/multicloud/aliyun/elasticcache_instance.go
Labels: size/XS

#560 Automated cherry pick of #558: fix(aliyun): avoid panic when get redis cache mod
  pkg/multicloud/aliyun/elasticcache_instance.go
Labels: size/XS

#557 fix(region): move sslcert from Region to CloudProvider
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aliyun/shell/sslcertificate.go
  pkg/multicloud/aliyun/sslcertificate.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/shell/sslcertificate.go
  pkg/multicloud/huawei/sslcertificate.go
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
Labels: size/L, do-not-merge/work-in-progress

#561 fix(qcloud): ssl
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/certificate.go
  pkg/multicloud/qcloud/shell/loadbalancer.go
Labels: size/L

#562 fix(pve): vm ip with ipv4
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#563 Automated cherry pick of #562: fix(pve): vm ip with ipv4
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#564 Automated cherry pick of #562: fix(pve): vm ip with ipv4
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#566 Automated cherry pick of #565: fix(volc): save image
  pkg/multicloud/volcengine/image.go
Labels: size/XS

#567 fix(esxi): preallocation vdisk
  pkg/apis/compute/disk_const.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/disk_base.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/remotefile/disk.go
Labels: size/L

#568 Automated cherry pick of #567: fix(esxi): preallocation vdisk
  pkg/apis/compute/disk_const.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/disk_base.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/remotefile/disk.go
Labels: size/L

#569 fix(azure): vm refresh panic
  pkg/multicloud/azure/region.go
Labels: size/S

#570 Automated cherry pick of #569: fix(azure): vm refresh panic
  pkg/multicloud/azure/region.go
Labels: size/S

#572 fix(oracle): support oracle
  cmd/ocli/main.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/loader/loader.go
  pkg/multicloud/oracle/instance.go
  pkg/multicloud/oracle/ocli/main.go
  pkg/multicloud/oracle/oracle.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/oracle/region.go
  pkg/multicloud/oracle/shell/compartment.go
  pkg/multicloud/oracle/shell/instance.go
  pkg/multicloud/oracle/shell/printutil.go
  pkg/multicloud/oracle/shell/region.go
  vendor/github.com/oracle/oci-go-sdk/LICENSE.txt
  vendor/github.com/oracle/oci-go-sdk/NOTICE.txt
  vendor/github.com/oracle/oci-go-sdk/common/client.go
  vendor/github.com/oracle/oci-go-sdk/common/common.go
  vendor/github.com/oracle/oci-go-sdk/common/configuration.go
  vendor/github.com/oracle/oci-go-sdk/common/errors.go
  vendor/github.com/oracle/oci-go-sdk/common/helpers.go
  vendor/github.com/oracle/oci-go-sdk/common/http.go
  vendor/github.com/oracle/oci-go-sdk/common/http_signer.go
  vendor/github.com/oracle/oci-go-sdk/common/log.go
  vendor/github.com/oracle/oci-go-sdk/common/retry.go
  vendor/github.com/oracle/oci-go-sdk/common/version.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/cloudinit/cloudconfig.go
  vendor/yunion.io/x/pkg/util/netutils/netutils.go
  vendor/yunion.io/x/pkg/util/printutils/printjson.go
  vendor/yunion.io/x/pkg/util/shellutils/edit.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/XXL

#573 Automated cherry pick of #572: fix(oracle): support oracle
  cmd/ocli/main.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/loader/loader.go
  pkg/multicloud/oracle/instance.go
  pkg/multicloud/oracle/ocli/main.go
  pkg/multicloud/oracle/oracle.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/oracle/region.go
  pkg/multicloud/oracle/shell/compartment.go
  pkg/multicloud/oracle/shell/instance.go
  pkg/multicloud/oracle/shell/printutil.go
  pkg/multicloud/oracle/shell/region.go
  vendor/github.com/oracle/oci-go-sdk/LICENSE.txt
  vendor/github.com/oracle/oci-go-sdk/NOTICE.txt
  vendor/github.com/oracle/oci-go-sdk/common/client.go
  vendor/github.com/oracle/oci-go-sdk/common/common.go
  vendor/github.com/oracle/oci-go-sdk/common/configuration.go
  vendor/github.com/oracle/oci-go-sdk/common/errors.go
  vendor/github.com/oracle/oci-go-sdk/common/helpers.go
  vendor/github.com/oracle/oci-go-sdk/common/http.go
  vendor/github.com/oracle/oci-go-sdk/common/http_signer.go
  vendor/github.com/oracle/oci-go-sdk/common/log.go
  vendor/github.com/oracle/oci-go-sdk/common/retry.go
  vendor/github.com/oracle/oci-go-sdk/common/version.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/cloudinit/cloudconfig.go
  vendor/yunion.io/x/pkg/util/netutils/netutils.go
  vendor/yunion.io/x/pkg/util/printutils/printjson.go
  vendor/yunion.io/x/pkg/util/shellutils/edit.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/XXL

#576 fix(awscli): fix aws dbinstance desc tag
  pkg/multicloud/aws/dbinstance.go
Labels: size/S

#574 fix(gcp): delete keypair
  pkg/multicloud/google/instance.go
Labels: size/S

#575 Automated cherry pick of #574: fix(gcp): delete keypair
  pkg/multicloud/google/instance.go
Labels: size/S

#571 feat(region): aws&huawei add cdn resource sync
  pkg/cloudprovider/dnszone.go
  pkg/multicloud/aliyun/dns_domain_record.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/cdn.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/cdn.go
  pkg/multicloud/huawei/cdn.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/shell/cdn.go
Labels: size/XL

#580 fix(qcloud): lb ip addr
  pkg/multicloud/qcloud/loadbalancer.go
Labels: size/XS

#581 Automated cherry pick of #580: fix(qcloud): lb ip addr
  pkg/multicloud/qcloud/loadbalancer.go
Labels: size/XS

#583 fix(qcloud): lb domain name
  pkg/multicloud/qcloud/loadbalancer.go
Labels: size/XS

#584 Automated cherry pick of #583: fix(qcloud): lb domain name
  pkg/multicloud/qcloud/loadbalancer.go
Labels: size/XS

#586 fix(region): k8s tag
  pkg/multicloud/aliyun/tag_base.go
  pkg/multicloud/tag_base.go
Labels: size/S

#587 Automated cherry pick of #586: fix(region): k8s tag
  pkg/multicloud/aliyun/tag_base.go
  pkg/multicloud/tag_base.go
Labels: size/S

#588 Automated cherry pick of #586: fix(region): k8s tag
  pkg/multicloud/aliyun/tag_base.go
  pkg/multicloud/tag_base.go
Labels: size/S

#589 fix(esxi): cpu sockets
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/remotefile/instance.go
Labels: size/M

#590 Automated cherry pick of #589: fix(esxi): cpu sockets
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/remotefile/instance.go
Labels: size/M

#591 fix(zstack): shared block storage
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/storage.go
Labels: size/S

#592 Automated cherry pick of #591: fix(zstack): shared block storage
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/storage.go
Labels: size/S

#595 fix(apsara): 避免死循环
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/host.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/apsara/storage.go
  pkg/multicloud/apsara/vpc.go
Labels: size/S

#596 Automated cherry pick of #595: fix(apsara): 避免死循环
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/host.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/apsara/storage.go
  pkg/multicloud/apsara/vpc.go
Labels: size/S

#597 fix(huawei): api pretty
  pkg/multicloud/huawei/cdn.go
  pkg/multicloud/huawei/clouduser.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/modelarts_pool.go
  pkg/multicloud/huawei/modelarts_pool_sku.go
  pkg/multicloud/huawei/monitor.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/sslcertificate.go
Labels: size/L

#598 fix: add extra api
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_invoke.go
  pkg/multicloud/aws/container.go
  pkg/multicloud/aws/dynamodb.go
  pkg/multicloud/aws/kinesis.go
  pkg/multicloud/aws/lambda.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/contanier.go
  pkg/multicloud/aws/shell/dynamodb.go
  pkg/multicloud/aws/shell/kinesis.go
  pkg/multicloud/aws/shell/lambda.go
  pkg/multicloud/huawei/functiongraph.go
  pkg/multicloud/huawei/gaussdb_mysql.go
  pkg/multicloud/huawei/gaussdb_nosql.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/shell/functions.go
  pkg/multicloud/huawei/shell/gaussdb_mysql.go
  pkg/multicloud/huawei/shell/gaussdb_nosql.go
Labels: size/XXL

#593 feature: support esxi subips
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/esxi/vnic.go
Labels: size/M

#594 Automated cherry pick of #593: feature: support esxi subips
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/esxi/vnic.go
Labels: size/M

#599 fix(qcloud): mac addr
  pkg/multicloud/huawei/gaussdb_mysql.go
  pkg/multicloud/huawei/gaussdb_nosql.go
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/instancenic.go
  pkg/multicloud/remotefile/instancenic.go
Labels: size/S

#600 Automated cherry pick of #599: fix(qcloud): mac addr
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/instancenic.go
  pkg/multicloud/remotefile/instancenic.go
Labels: size/S

#601 Automated cherry pick of #599: fix(qcloud): mac addr
  pkg/multicloud/qcloud/certificate.go
  pkg/multicloud/qcloud/instancenic.go
  pkg/multicloud/remotefile/instancenic.go
Labels: size/S
