Repository yunionio/cloudmux, pull requests merged in 2023-03, with the labels that each got.

#201 add HCSO monitor
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/monitor.go
  pkg/multicloud/hcso/shell/monitor.go
Labels: size/L, lgtm

#202 Automated cherry pick of #201: add HCSO monitor
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/monitor.go
  pkg/multicloud/hcso/shell/monitor.go
Labels: size/L

#203 fix(apsara): projects
  pkg/multicloud/apsara/organization.go
Labels: apsara

#204 Automated cherry pick of #203: fix(apsara): projects
  pkg/multicloud/apsara/organization.go
Labels: size/S

#205 fix hcso rds monitor
  pkg/multicloud/hcso/monitor.go
Labels: size/XS

#206 Automated cherry pick of #205: fix hcso rds monitor
  pkg/multicloud/hcso/monitor.go
Labels: size/XS

#207 addHcsoEcsMemDisk
  pkg/multicloud/hcso/monitor.go
Labels: size/XS

#211 fix(aws): dns zone name
  pkg/multicloud/aws/dnshostedzone.go
Labels: size/XS

#196 Automated cherry pick of #195: Feature/implement bingocloud
  pkg/multicloud/bingocloud/account.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/disk.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/bingocloud/instance_snapshot.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/bingocloud/quotas.go
  pkg/multicloud/bingocloud/region.go
  pkg/multicloud/bingocloud/securitygroup.go
  pkg/multicloud/bingocloud/snapshot.go
  pkg/multicloud/bingocloud/storage.go
Labels: size/L

#195 Feature/implement bingocloud
  pkg/multicloud/bingocloud/account.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/disk.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/bingocloud/instance_snapshot.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/bingocloud/quotas.go
  pkg/multicloud/bingocloud/region.go
  pkg/multicloud/bingocloud/securitygroup.go
  pkg/multicloud/bingocloud/snapshot.go
  pkg/multicloud/bingocloud/storage.go
Labels: size/L

#213 fix(remote): fixGetIBucketById
  pkg/multicloud/remotefile/region.go
Labels: size/XS

#214 Automated cherry pick of #213: fix(remote): fixGetIBucketById
  pkg/multicloud/remotefile/region.go
Labels: size/XS

#215 fix(aliyun): disk snapshot sync
  pkg/multicloud/aliyun/disk.go
  pkg/multicloud/apsara/disk.go
Labels: size/S

#218 Automated cherry pick of #217: fix jdcloud and ctyun accountConnectTest
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/jdcloud/balance.go
Labels: size/XS

#221 Automated cherry pick of #220: fix(hcs): hcs url
  pkg/multicloud/hcs/hcs.go
Labels: size/XS

#222 fix(hcs): auth url
  pkg/multicloud/hcs/hcs.go
Labels: size/XS

#226 fix(apsara): add metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/apsara/monitor.go
Labels: size/L

#227 Automated cherry pick of #226: fix(apsara): add metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/apsara/monitor.go
Labels: size/L

#219 add ICloudResource GetDescription
  pkg/cloudprovider/resources.go
  pkg/multicloud/bingocloud/instance_type.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/loadbalancer_backend.go
  pkg/multicloud/google/loadbalancer_backendgroup.go
  pkg/multicloud/google/loadbalancer_listener.go
  pkg/multicloud/google/loadbalancer_listenerrule.go
  pkg/multicloud/google/network.go
  pkg/multicloud/google/resourcebase.go
  pkg/multicloud/remotefile/instance.go
  pkg/multicloud/remotefile/projects.go
  pkg/multicloud/remotefile/resource.go
  pkg/multicloud/resource_base.go
Labels: size/L

#228 Automated cherry pick of #219: add ICloudResource GetDescription
  pkg/cloudprovider/resources.go
  pkg/multicloud/bingocloud/instance_type.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/loadbalancer_backend.go
  pkg/multicloud/google/loadbalancer_backendgroup.go
  pkg/multicloud/google/loadbalancer_listener.go
  pkg/multicloud/google/loadbalancer_listenerrule.go
  pkg/multicloud/google/network.go
  pkg/multicloud/google/resourcebase.go
  pkg/multicloud/remotefile/instance.go
  pkg/multicloud/remotefile/projects.go
  pkg/multicloud/remotefile/resource.go
  pkg/multicloud/resource_base.go
Labels: size/L

#230 Automated cherry pick of #229: fix(hcsocli): add hcso requestWithRetry
  go.mod
  go.sum
  pkg/multicloud/hcso/hcso.go
Labels: size/M

#229 fix(hcsocli): add hcso requestWithRetry
  go.mod
  go.sum
  pkg/multicloud/hcso/hcso.go
Labels: size/M

#232 fix(hcsocli): fix modelarts refresh bug
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M, lgtm

#233 Automated cherry pick of #232: fix(hcsocli): fix modelarts refresh bug
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#234 fix(hcsocli): add slb monitor
  pkg/cloudprovider/metrics.go
  pkg/multicloud/hcso/monitor.go
Labels: size/M

#235 Automated cherry pick of #234: fix(hcsocli): add slb monitor
  pkg/cloudprovider/metrics.go
  pkg/multicloud/hcso/monitor.go
Labels: size/M

#236 fix(hcsocli): fix hcso\huawei modelarts getStatus and refresh
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#237 Automated cherry pick of #236: fix(hcsocli): fix hcso\huawei modelarts getStatus and refresh
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M
