Repository yunionio/cloudmux, pull requests merged in 2023-10, with the labels that each got.

#458 fix(aws): avoid nil panic
  pkg/multicloud/aws/instance.go
Labels: size/S

#437 feat(all): support set cors
  pkg/cloudprovider/objectstore.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/google/bucket.go
  pkg/multicloud/google/shell/bucket.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/object.go
  pkg/multicloud/huawei/obs/auth.go
  pkg/multicloud/huawei/obs/authV2.go
  pkg/multicloud/huawei/obs/authV4.go
  pkg/multicloud/huawei/obs/callback.go
  pkg/multicloud/huawei/obs/client.go
  pkg/multicloud/huawei/obs/client_base.go
  pkg/multicloud/huawei/obs/client_bucket.go
  pkg/multicloud/huawei/obs/client_object.go
  pkg/multicloud/huawei/obs/client_other.go
  pkg/multicloud/huawei/obs/client_part.go
  pkg/multicloud/huawei/obs/client_resume.go
  pkg/multicloud/huawei/obs/conf.go
  pkg/multicloud/huawei/obs/const.go
  pkg/multicloud/huawei/obs/convert.go
  pkg/multicloud/huawei/obs/doc.go
  pkg/multicloud/huawei/obs/extension.go
  pkg/multicloud/huawei/obs/http.go
  pkg/multicloud/huawei/obs/log.go
  pkg/multicloud/huawei/obs/mime.go
  pkg/multicloud/huawei/obs/model.go
  pkg/multicloud/huawei/obs/model_base.go
  pkg/multicloud/huawei/obs/model_bucket.go
  pkg/multicloud/huawei/obs/model_header.go
  pkg/multicloud/huawei/obs/model_object.go
  pkg/multicloud/huawei/obs/model_other.go
  pkg/multicloud/huawei/obs/model_part.go
  pkg/multicloud/huawei/obs/model_response.go
  pkg/multicloud/huawei/obs/pool.go
  pkg/multicloud/huawei/obs/provider.go
  pkg/multicloud/huawei/obs/temporary.go
  pkg/multicloud/huawei/obs/temporary_createSignedUrl.go
  pkg/multicloud/huawei/obs/temporary_other.go
  pkg/multicloud/huawei/obs/temporary_signedUrl.go
  pkg/multicloud/huawei/obs/trait.go
  pkg/multicloud/huawei/obs/trait_base.go
  pkg/multicloud/huawei/obs/trait_bucket.go
  pkg/multicloud/huawei/obs/trait_object.go
  pkg/multicloud/huawei/obs/trait_other.go
  pkg/multicloud/huawei/obs/trait_part.go
  pkg/multicloud/huawei/obs/transfer.go
  pkg/multicloud/huawei/obs/type.go
  pkg/multicloud/huawei/obs/util.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/objectstore/shell.go
Labels: size/XXL

#459 Automated cherry pick of #437: feat(all): support set cors
  pkg/cloudprovider/objectstore.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/google/bucket.go
  pkg/multicloud/google/shell/bucket.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/object.go
  pkg/multicloud/huawei/obs/auth.go
  pkg/multicloud/huawei/obs/authV2.go
  pkg/multicloud/huawei/obs/authV4.go
  pkg/multicloud/huawei/obs/callback.go
  pkg/multicloud/huawei/obs/client.go
  pkg/multicloud/huawei/obs/client_base.go
  pkg/multicloud/huawei/obs/client_bucket.go
  pkg/multicloud/huawei/obs/client_object.go
  pkg/multicloud/huawei/obs/client_other.go
  pkg/multicloud/huawei/obs/client_part.go
  pkg/multicloud/huawei/obs/client_resume.go
  pkg/multicloud/huawei/obs/conf.go
  pkg/multicloud/huawei/obs/const.go
  pkg/multicloud/huawei/obs/convert.go
  pkg/multicloud/huawei/obs/doc.go
  pkg/multicloud/huawei/obs/extension.go
  pkg/multicloud/huawei/obs/http.go
  pkg/multicloud/huawei/obs/log.go
  pkg/multicloud/huawei/obs/mime.go
  pkg/multicloud/huawei/obs/model.go
  pkg/multicloud/huawei/obs/model_base.go
  pkg/multicloud/huawei/obs/model_bucket.go
  pkg/multicloud/huawei/obs/model_header.go
  pkg/multicloud/huawei/obs/model_object.go
  pkg/multicloud/huawei/obs/model_other.go
  pkg/multicloud/huawei/obs/model_part.go
  pkg/multicloud/huawei/obs/model_response.go
  pkg/multicloud/huawei/obs/pool.go
  pkg/multicloud/huawei/obs/provider.go
  pkg/multicloud/huawei/obs/temporary.go
  pkg/multicloud/huawei/obs/temporary_createSignedUrl.go
  pkg/multicloud/huawei/obs/temporary_other.go
  pkg/multicloud/huawei/obs/temporary_signedUrl.go
  pkg/multicloud/huawei/obs/trait.go
  pkg/multicloud/huawei/obs/trait_base.go
  pkg/multicloud/huawei/obs/trait_bucket.go
  pkg/multicloud/huawei/obs/trait_object.go
  pkg/multicloud/huawei/obs/trait_other.go
  pkg/multicloud/huawei/obs/trait_part.go
  pkg/multicloud/huawei/obs/transfer.go
  pkg/multicloud/huawei/obs/type.go
  pkg/multicloud/huawei/obs/util.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/objectstore/shell.go
Labels: size/XXL

#460 fix(azure): remove classic resource
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/classic_disk.go
  pkg/multicloud/azure/classic_eip.go
  pkg/multicloud/azure/classic_host.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/classic_instancenic.go
  pkg/multicloud/azure/classic_instancesize.go
  pkg/multicloud/azure/classic_network.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_snapshot.go
  pkg/multicloud/azure/classic_storage.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/classic_wire.go
  pkg/multicloud/azure/data_disk.go
  pkg/multicloud/azure/image.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/disk.go
  pkg/multicloud/azure/shell/eip.go
  pkg/multicloud/azure/shell/instance.go
  pkg/multicloud/azure/zone.go
Labels: size/XXL

#461 Automated cherry pick of #460: fix(azure): remove classic resource
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/classic_disk.go
  pkg/multicloud/azure/classic_eip.go
  pkg/multicloud/azure/classic_host.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/classic_instancenic.go
  pkg/multicloud/azure/classic_instancesize.go
  pkg/multicloud/azure/classic_network.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_snapshot.go
  pkg/multicloud/azure/classic_storage.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/classic_wire.go
  pkg/multicloud/azure/data_disk.go
  pkg/multicloud/azure/image.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/disk.go
  pkg/multicloud/azure/shell/eip.go
  pkg/multicloud/azure/shell/instance.go
  pkg/multicloud/azure/zone.go
Labels: size/XXL

#467 fix: azure cloud group
  pkg/multicloud/azure/cloudgroup.go
Labels: size/XS

#468 Automated cherry pick of #467: fix: azure cloud group
  pkg/multicloud/azure/cloudgroup.go
Labels: size/XS

#469 Automated cherry pick of #467: fix: azure cloud group
  pkg/multicloud/azure/cloudgroup.go
Labels: size/XS

#470 fix: aws userdata
  pkg/multicloud/aws/instance.go
Labels: size/XS

#471 Automated cherry pick of #470: fix: aws userdata
  pkg/multicloud/aws/instance.go
Labels: size/XS

#472 fix(ctyun): remove ctyun env parameter
  pkg/multicloud/ctyun/provider/provider.go
Labels: size/XS

#473 Automated cherry pick of #472: fix(ctyun): remove ctyun env parameter
  pkg/multicloud/ctyun/provider/provider.go
Labels: size/XS

#478 fix(ctyun): invalid access key error
  pkg/multicloud/ctyun/ctyun.go
Labels: size/XS

#479 Automated cherry pick of #478: fix(ctyun): invalid access key error
  pkg/multicloud/ctyun/ctyun.go
Labels: size/XS

#483 fix: vmware sync wires revisit
  pkg/multicloud/esxi/compact_ips.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/tags.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/esxi/wire.go
Labels: size/M

#486 fix(aws): aws lb panic
  pkg/multicloud/aws/loadbalancer.go
Labels: size/XS

#487 Automated cherry pick of #486: fix(aws): aws lb panic
  pkg/multicloud/aws/loadbalancer.go
Labels: size/XS

#488 fix: more details when esxi get_network_by_id error
  pkg/multicloud/esxi/devtools.go
Labels: size/XS

#489 Automated cherry pick of #488: fix: more details when esxi get_network_by_id error
  pkg/multicloud/esxi/devtools.go
Labels: size/XS

#492 fix(aws): eip not found error
  pkg/multicloud/aws/eip.go
Labels: size/XS

#493 Automated cherry pick of #492: fix(aws): eip not found error
  pkg/multicloud/aws/eip.go
Labels: size/XS

#494 Automated cherry pick of #492: fix(aws): eip not found error
  pkg/multicloud/aws/eip.go
Labels: size/XS

#495 fix(aliyun): cloud_auto enable burst
  pkg/multicloud/aliyun/instance.go
Labels: size/M

#500 Automated cherry pick of #495: fix(aliyun): cloud_auto enable burst
  pkg/multicloud/aliyun/instance.go
Labels: size/M

#501 fix: secgroup rule create
  pkg/multicloud/aliyun/secgrouprule.go
  pkg/multicloud/apsara/secgrouprule.go
  pkg/multicloud/huawei/secgrouprule.go
  pkg/multicloud/qcloud/securitygroup.go
Labels: size/M

#504 Automated cherry pick of #503: fix(esxi): single esxi host not support tags
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/XS

#506 fix: secgroup rule update
  pkg/multicloud/aliyun/secgrouprule.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/ctyun/secrules.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/qcloud/secgrouprule.go
Labels: size/L

#507 Automated cherry pick of #506: fix: secgroup rule update
  pkg/multicloud/aliyun/secgrouprule.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/ctyun/secrules.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/qcloud/secgrouprule.go
Labels: size/L

#508 fix: aliyun disk burst
  pkg/multicloud/aliyun/disk.go
  pkg/multicloud/aliyun/storage.go
Labels: size/S

#515 fix(azure): secgroup delete
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/apsara/vpc.go
  pkg/multicloud/azure/instancenic.go
  pkg/multicloud/azure/securitygroup.go
Labels: size/M

#516 Automated cherry pick of #515: fix(azure): secgroup delete
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/apsara/vpc.go
  pkg/multicloud/azure/instancenic.go
  pkg/multicloud/azure/securitygroup.go
Labels: size/M

#517 fix(region): aws default secgroup delete
  pkg/multicloud/aws/securitygroup.go
Labels: size/XS

#518 Automated cherry pick of #517: fix(region): aws default secgroup delete
  pkg/multicloud/aws/securitygroup.go
Labels: size/XS

#519 fix(volc): security group delete
  pkg/multicloud/volcengine/region.go
  pkg/multicloud/volcengine/securitygroup.go
  pkg/multicloud/volcengine/shell/secgroup.go
Labels: size/S

#523 Automated cherry pick of #522: fix: add interface for region get vms
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/instance.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/azure/host.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/bingocloud/region.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ecloud/region.go
  pkg/multicloud/esxi/fakeregion.go
  pkg/multicloud/google/region.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/jdcloud/region.go
  pkg/multicloud/nutanix/region.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/proxmox/instance.go
  pkg/multicloud/proxmox/region.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/region_base.go
  pkg/multicloud/remotefile/region.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/volcengine/host.go
  pkg/multicloud/volcengine/instance.go
  pkg/multicloud/volcengine/region.go
  pkg/multicloud/volcengine/shell/instance.go
  pkg/multicloud/zstack/region.go
Labels: size/L

#526 fix: volc misc fix
  pkg/multicloud/volcengine/disk.go
  pkg/multicloud/volcengine/instance.go
  pkg/multicloud/volcengine/region.go
  pkg/multicloud/volcengine/shell/disk.go
  pkg/multicloud/volcengine/storage.go
Labels: size/M
