Repository yunionio/cloudmux, pull requests merged in 2023-07, with the labels that each got.

#331 fix(azure): map read
  pkg/multicloud/azure/azure.go
Labels: size/XS

#332 Automated cherry pick of #331: fix(azure): map read
  pkg/multicloud/azure/azure.go
Labels: size/XS

#336 fix(esxi): hostname
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/XS

#337 Automated cherry pick of #336: fix(esxi): hostname
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/XS

#340 fix(proxmox): error msg
  go.mod
  go.sum
  pkg/multicloud/azure/azure.go
  pkg/multicloud/google/google.go
  pkg/multicloud/hcso/client/modules/manager_base.go
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/proxmox/proxmox.go
Labels: size/L

#341 Automated cherry pick of #340: fix(proxmox): error msg
  go.mod
  go.sum
  pkg/multicloud/azure/azure.go
  pkg/multicloud/google/google.go
  pkg/multicloud/hcso/client/modules/manager_base.go
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/proxmox/proxmox.go
Labels: size/L

#344 fix(huawei): metric
  pkg/multicloud/huawei/monitor.go
Labels: size/M

#346 Automated cherry pick of #344: fix(huawei): metric
  pkg/multicloud/huawei/monitor.go
Labels: size/M

#342 fix(hcsocli): add defaultRegion for climc
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/hcso/project.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/project.go
Labels: size/S

#345 Automated cherry pick of #342: fix(hcsocli): add defaultRegion for climc
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/hcso/project.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/project.go
Labels: size/S

#347 fix(esxi): local storage image
  pkg/multicloud/esxi/shell/images.go
  pkg/multicloud/esxi/storagecache.go
Labels: size/L

#348 Automated cherry pick of #347: fix(esxi): local storage image
  pkg/multicloud/esxi/shell/images.go
  pkg/multicloud/esxi/storagecache.go
Labels: size/L

#351 fix: update esxi credential with host
  pkg/multicloud/esxi/provider/provider.go
  scripts/cherry_pick_pull.sh
Labels: size/S

#333 fix: refactor aws redis
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/elasticache_instance.go
  pkg/multicloud/aws/elasticache_instancetype.go
  pkg/multicloud/aws/elasticache_memcached.go
  pkg/multicloud/aws/elasticache_parameter.go
  pkg/multicloud/aws/elasticache_snapshot.go
  pkg/multicloud/aws/elasticache_user.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/elasticache.go
Labels: size/XXL

#355 fix(aliyun): eni sync
  pkg/multicloud/aliyun/networkinterfaces.go
  pkg/multicloud/aliyun/shell/networkinterface.go
Labels: size/M

#356 Automated cherry pick of #355: fix(aliyun): eni sync
  pkg/multicloud/aliyun/networkinterfaces.go
  pkg/multicloud/aliyun/shell/networkinterface.go
Labels: size/M

#357 fix: show currency for balance
  cmd/cmx/shell/balance.go
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/proxmox/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/remotefile/provider/provider.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/zstack/provider/provider.go
Labels: size/L

#359 fix(aws): secgroup rule
  pkg/multicloud/aws/securitygroup.go
Labels: size/XS

#363 Automated cherry pick of #362: fix(apsara): apsara https
  pkg/multicloud/apsara/apsara.go
Labels: size/XS
