Repository yunionio/cloudmux, pull requests merged in 2023-04, with the labels that each got.

#238 fix(hcsocli): request akSign
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#239 Automated cherry pick of #238: fix(hcsocli): request akSign
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#240 fix(apsara): bucket size metric
  pkg/multicloud/apsara/monitor.go
Labels: size/M

#242 fix(apsara): process number
  pkg/multicloud/apsara/monitor.go
Labels: size/M

#246 fix(bingo): metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/bingocloud/monitor.go
Labels: size/S

#247 Automated cherry pick of #246: fix(bingo): metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/bingocloud/monitor.go
Labels: size/S

#252 fix(openstack): create keypair
  pkg/multicloud/openstack/openstack.go
Labels: size/XS

#253 Automated cherry pick of #252: fix(openstack): create keypair
  pkg/multicloud/openstack/openstack.go
Labels: size/XS

#254 fix(openstack): openstack vm ip
  pkg/multicloud/openstack/instancenic.go
Labels: size/S

#258 fix(hcsocli): fixModelartsRefreshForCreate
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/hcso/shell/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
  pkg/multicloud/huawei/shell/modelarts_pool.go
  pkg/multicloud/region_base.go
Labels: size/L

#261 Automated cherry pick of #258: fix(hcsocli): fixModelartsRefreshForCreate
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/hcso/shell/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
  pkg/multicloud/huawei/shell/modelarts_pool.go
  pkg/multicloud/region_base.go
Labels: size/L

#262 fix(esxi): inject ovf file
  pkg/multicloud/esxi/ovf.go
  pkg/multicloud/esxi/storage.go
Labels: size/M

#264 fix(hcsocli): add modelarts get status message
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
  pkg/multicloud/region_base.go
Labels: size/S

#265 Automated cherry pick of #264: fix(hcsocli): add modelarts get status message
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
  pkg/multicloud/region_base.go
Labels: size/S

#266 fix: remotefile
  pkg/multicloud/remotefile/region.go
Labels: size/M

#268 fix(azure): support switch pull disk usage metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/azure/monitor.go
Labels: size/L

#269 Automated cherry pick of #268: fix(azure): support switch pull disk usage metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/azure/monitor.go
Labels: size/L

#270 fix(proxmox): misc fix
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#272 fix(aws): aws region meta
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/region.go
Labels: size/M

#260 fix: secgroup sync
  go.mod
  go.sum
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aliyun/shell/secgroup.go
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/apsara/securitygroup.go
  pkg/multicloud/apsara/shell/secgroup.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/azure/shell/secgroup.go
  pkg/multicloud/bingocloud/securitygroup.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/ctyun/shell/secgroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/hcso/securitygroup.go
  pkg/multicloud/hcso/shell/secgroup.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/secgroup.go
  pkg/multicloud/jdcloud/securitygroup.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/ucloud/shell/secgroup.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
Labels: size/XXL

#274 Automated cherry pick of #260: fix: secgroup sync
  go.mod
  go.sum
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aliyun/shell/secgroup.go
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/apsara/region.go
  pkg/multicloud/apsara/securitygroup.go
  pkg/multicloud/apsara/shell/secgroup.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/azure/shell/secgroup.go
  pkg/multicloud/bingocloud/securitygroup.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/ctyun/shell/secgroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/hcso/securitygroup.go
  pkg/multicloud/hcso/shell/secgroup.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/secgroup.go
  pkg/multicloud/jdcloud/securitygroup.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/ucloud/shell/secgroup.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
Labels: size/XXL
