Repository yunionio/cloudmux, pull requests merged in 2023-05, with the labels that each got.

#278 Automated cherry pick of #277: fix(aws): redis tags
  pkg/multicloud/aws/elasticache_instance.go
  pkg/multicloud/aws/region.go
Labels: size/M

#279 fix(proxmox): panic
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#280 Automated cherry pick of #279: fix(proxmox): panic
  pkg/multicloud/proxmox/instance.go
Labels: size/XS

#281 fix(region): avoid div zero
  pkg/multicloud/azure/securitygroup.go
Labels: size/XS

#282 Automated cherry pick of #281: fix(region): avoid div zero
  pkg/multicloud/azure/securitygroup.go
Labels: size/XS

#283 fix(jdcloud): sync jdcloud host name
  pkg/multicloud/jdcloud/host.go
  pkg/multicloud/jdcloud/region.go
  pkg/multicloud/jdcloud/zone.go
Labels: size/XS

#276 fix(aws): support eks
  pkg/apis/compute/kube_cluster.go
  pkg/cloudprovider/kube_cluster.go
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/waitstatus.go
  pkg/multicloud/aliyun/kube_cluster.go
  pkg/multicloud/aliyun/kube_node_pools.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_invoke.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/eks.go
  pkg/multicloud/aws/eks_node_group.go
  pkg/multicloud/aws/iam_role.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/eks.go
  pkg/multicloud/aws/shell/eks_nodegroup.go
  pkg/multicloud/aws/shell/iam_role.go
  pkg/multicloud/azure/kube_cluster.go
  pkg/multicloud/azure/kube_node_pools.go
  pkg/multicloud/qcloud/kube_clusters.go
  pkg/multicloud/qcloud/kube_node_pools.go
  pkg/multicloud/region_base.go
Labels: size/XXL

#289 fix(aws): tag index
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/elasticache_instance.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/utils.go
Labels: size/M

#290 Automated cherry pick of #289: fix(aws): tag index
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/elasticache_instance.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/utils.go
Labels: size/M

#291 fix(aws): network public ip
  pkg/cloudprovider/network.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/wire.go
Labels: size/L

#293 fix(remotefile): fix GetIDisks storage
  pkg/multicloud/remotefile/disk.go
  pkg/multicloud/remotefile/instance.go
Labels: size/S
