Repository yunionio/cloudmux, pull requests merged in 2024-08, with the labels that each got.

#1030 fix(huawei): support huawei intl account query balance
  pkg/multicloud/huawei/huawei.go
Labels: size/M

#1031 Automated cherry pick of #1030: fix(huawei): support huawei intl account query balance
  pkg/multicloud/huawei/huawei.go
Labels: size/M

#1032 Automated cherry pick of #1030: fix(huawei): support huawei intl account query balance
  pkg/multicloud/huawei/huawei.go
Labels: size/L

#1033 Automated cherry pick of #1030: fix(huawei): support huawei intl account query balance
  pkg/multicloud/huawei/huawei.go
Labels: size/L

#1034 fix(pve): supports cpu architecture differentiation
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#1035 Automated cherry pick of #1034: fix(pve): supports cpu architecture differentiation
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#1036 Automated cherry pick of #1034: fix(pve): supports cpu architecture differentiation
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#1037 Automated cherry pick of #1034: fix(pve): supports cpu architecture differentiation
  pkg/multicloud/proxmox/host.go
  pkg/multicloud/proxmox/instance.go
Labels: size/S

#1038 fix(qcloud): lb backend ip sync
  pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/XS

#1039 Automated cherry pick of #1038: fix(qcloud): lb backend ip sync
  pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/XS

#1040 Automated cherry pick of #1038: fix(qcloud): lb backend ip sync
  pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/XS

#1041 Automated cherry pick of #1038: fix(qcloud): lb backend ip sync
  pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/XS

#1042 fix(huawei): more details huawei error info
  pkg/multicloud/huawei/huawei.go
Labels: size/M

#1043 Automated cherry pick of #1042: fix(huawei): more details huawei error info
  pkg/multicloud/huawei/huawei.go
Labels: size/M

#970 fix: ceph reuse http connection (reported by GDYT)
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#1045 Automated cherry pick of #970: fix: ceph reuse http connection (reported by GDYT)
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#1046 Automated cherry pick of #970: fix: ceph reuse http connection (reported by GDYT)
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#1047 Automated cherry pick of #970: fix: ceph reuse http connection (reported by GDYT)
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#1044 fix(aws): add dns traffic policy api
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/dns_domain_record.go
  pkg/multicloud/aliyun/gtm.go
  pkg/multicloud/aliyun/gtm3.go
  pkg/multicloud/aliyun/private_zone_record.go
  pkg/multicloud/aliyun/shell/dns_domain.go
  pkg/multicloud/aliyun/shell/gtm.go
  pkg/multicloud/aliyun/shell/gtm3.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/dns_traffic_policy.go
  pkg/multicloud/aws/dnsrecord.go
  pkg/multicloud/aws/shell/dns_traffic_policy.go
  pkg/multicloud/qcloud/dnspod_record.go
Labels: size/XL

#1049 Automated cherry pick of #1044: fix(aws): add dns traffic policy api
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/dns_domain_record.go
  pkg/multicloud/aliyun/gtm.go
  pkg/multicloud/aliyun/gtm3.go
  pkg/multicloud/aliyun/private_zone_record.go
  pkg/multicloud/aliyun/shell/dns_domain.go
  pkg/multicloud/aliyun/shell/gtm.go
  pkg/multicloud/aliyun/shell/gtm3.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/dns_traffic_policy.go
  pkg/multicloud/aws/dnsrecord.go
  pkg/multicloud/aws/shell/dns_traffic_policy.go
  pkg/multicloud/qcloud/dnspod_record.go
Labels: size/XL

#1048 Automated cherry pick of #1044: fix(aws): add dns traffic policy api
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/dns_domain_record.go
  pkg/multicloud/aliyun/gtm.go
  pkg/multicloud/aliyun/gtm3.go
  pkg/multicloud/aliyun/private_zone_record.go
  pkg/multicloud/aliyun/shell/dns_domain.go
  pkg/multicloud/aliyun/shell/gtm.go
  pkg/multicloud/aliyun/shell/gtm3.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/dns_traffic_policy.go
  pkg/multicloud/aws/dnsrecord.go
  pkg/multicloud/aws/shell/dns_traffic_policy.go
  pkg/multicloud/qcloud/dnspod_record.go
Labels: size/XL

#1053 Automated cherry pick of #1042: fix(huawei): more details huawei error info
  pkg/multicloud/huawei/huawei.go
Labels: size/M

#1050 fix(huawei): error code
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/saml_provider.go
Labels: size/XS

#1051 Automated cherry pick of #1050: fix(huawei): error code
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/saml_provider.go
Labels: size/XS

#1052 Automated cherry pick of #1050: fix(huawei): error code
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/saml_provider.go
Labels: size/XS
