Repository yunionio/cloudmux, pull requests merged in 2024-05, with the labels that each got.

#924 fix(azure): lb sync
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/eip.go
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancer_http_listener.go
  pkg/multicloud/azure/loadbalancer_props.go
  pkg/multicloud/azure/loadbalancerbackend.go
  pkg/multicloud/azure/loadbalancerbackendgroup.go
  pkg/multicloud/azure/loadbalancercert.go
  pkg/multicloud/azure/loadbalancerlistener.go
  pkg/multicloud/azure/loadbalancerlistenerrule.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/loadbalancer.go
Labels: size/XXL

#925 Automated cherry pick of #924: fix(azure): lb sync
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/eip.go
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancer_http_listener.go
  pkg/multicloud/azure/loadbalancer_props.go
  pkg/multicloud/azure/loadbalancerbackend.go
  pkg/multicloud/azure/loadbalancerbackendgroup.go
  pkg/multicloud/azure/loadbalancercert.go
  pkg/multicloud/azure/loadbalancerlistener.go
  pkg/multicloud/azure/loadbalancerlistenerrule.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/loadbalancer.go
Labels: size/XXL

#926 Automated cherry pick of #924: fix(azure): lb sync
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/eip.go
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancer_http_listener.go
  pkg/multicloud/azure/loadbalancer_props.go
  pkg/multicloud/azure/loadbalancerbackend.go
  pkg/multicloud/azure/loadbalancerbackendgroup.go
  pkg/multicloud/azure/loadbalancercert.go
  pkg/multicloud/azure/loadbalancerlistener.go
  pkg/multicloud/azure/loadbalancerlistenerrule.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/loadbalancer.go
Labels: size/XXL

#928 fix(zstack): shared storage
  pkg/apis/compute/storage_const.go
Labels: size/XS

#929 Automated cherry pick of #928: fix(zstack): shared storage
  pkg/apis/compute/storage_const.go
Labels: size/XS

#930 Automated cherry pick of #928: fix(zstack): shared storage
  pkg/apis/compute/storage_const.go
Labels: size/XS

#935 fix: cloudmux lock pkg tag at release/3.10
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/log/log.go
Labels: size/S

#936 fix: go mod vendor
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/log/log.go
  vendor/yunion.io/x/pkg/errors/consts.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
  vendor/yunion.io/x/pkg/util/netutils/http.go
  vendor/yunion.io/x/pkg/util/netutils/ipv6.go
  vendor/yunion.io/x/pkg/util/regutils/regutils.go
  vendor/yunion.io/x/pkg/util/seclib/seclib.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
Labels: size/L

#937 Automated cherry pick of #936: fix: go mod vendor
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/log/log.go
  vendor/yunion.io/x/pkg/errors/consts.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
  vendor/yunion.io/x/pkg/util/netutils/http.go
  vendor/yunion.io/x/pkg/util/netutils/ipv6.go
  vendor/yunion.io/x/pkg/util/regutils/regutils.go
  vendor/yunion.io/x/pkg/util/seclib/seclib.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
Labels: size/L

#938 Automated cherry pick of #936: fix: go mod vendor
  Makefile
Labels: size/XS

#940 Automated cherry pick of #939: fix(azure): web app
  pkg/cloudprovider/resources.go
  pkg/multicloud/azure/app_service_plan.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/loadbalancercert.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/app_service_plan.go
  pkg/multicloud/azure/shell/web_app.go
  pkg/multicloud/azure/subscription.go
  pkg/multicloud/azure/web_app.go
  pkg/multicloud/azure/web_app_backup.go
  pkg/multicloud/azure/web_app_certificate.go
  pkg/multicloud/azure/web_app_environment.go
  pkg/multicloud/azure/web_app_hybrid_connection.go
Labels: size/XXL

#939 fix(azure): web app
  pkg/cloudprovider/resources.go
  pkg/multicloud/azure/app_service_plan.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/loadbalancercert.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/app_service_plan.go
  pkg/multicloud/azure/shell/web_app.go
  pkg/multicloud/azure/subscription.go
  pkg/multicloud/azure/web_app.go
  pkg/multicloud/azure/web_app_backup.go
  pkg/multicloud/azure/web_app_certificate.go
  pkg/multicloud/azure/web_app_environment.go
  pkg/multicloud/azure/web_app_hybrid_connection.go
Labels: size/XXL

#941 Automated cherry pick of #939: fix(azure): web app
  pkg/cloudprovider/resources.go
  pkg/multicloud/azure/app_service_plan.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/loadbalancercert.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/app_service_plan.go
  pkg/multicloud/azure/shell/web_app.go
  pkg/multicloud/azure/subscription.go
  pkg/multicloud/azure/web_app.go
  pkg/multicloud/azure/web_app_backup.go
  pkg/multicloud/azure/web_app_certificate.go
  pkg/multicloud/azure/web_app_environment.go
  pkg/multicloud/azure/web_app_hybrid_connection.go
Labels: size/XXL

#942 fix(azure): web app attr
  pkg/multicloud/azure/shell/web_app.go
  pkg/multicloud/azure/web_app.go
Labels: size/M

#943 Automated cherry pick of #942: fix(azure): web app attr
  pkg/multicloud/azure/shell/web_app.go
  pkg/multicloud/azure/web_app.go
Labels: size/M

#944 Automated cherry pick of #942: fix(azure): web app attr
  pkg/multicloud/azure/shell/web_app.go
  pkg/multicloud/azure/web_app.go
Labels: size/M

#946 Automated cherry pick of #945: fix(qcloud): qcloud waf
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/waf_domain.go
  pkg/multicloud/aws/waf.go
  pkg/multicloud/azure/waf.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/waf.go
  pkg/multicloud/qcloud/waf.go
Labels: size/L

#947 Automated cherry pick of #945: fix(qcloud): qcloud waf
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/waf_domain.go
  pkg/multicloud/aws/waf.go
  pkg/multicloud/azure/waf.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/waf.go
  pkg/multicloud/qcloud/waf.go
Labels: size/L

#948 fix(huawei): avoid empty resp panic
  pkg/multicloud/huawei/huawei.go
Labels: size/XS

#949 Automated cherry pick of #948: fix(huawei): avoid empty resp panic
  pkg/multicloud/huawei/huawei.go
Labels: size/XS

#950 Automated cherry pick of #948: fix(huawei): avoid empty resp panic
  pkg/multicloud/huawei/huawei.go
Labels: size/XS

#954 fix(cephfs): delete cephfs dir
  pkg/multicloud/cephfs/dirs.go
  pkg/multicloud/cephfs/shell/cephfs.go
Labels: size/XS

#955 Automated cherry pick of #954: fix(cephfs): delete cephfs dir
  pkg/multicloud/cephfs/dirs.go
  pkg/multicloud/cephfs/shell/cephfs.go
Labels: size/XS

#958 fix(qcloud): add waf upstream info
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/waf.go
  pkg/multicloud/aliyun/waf_domain.go
  pkg/multicloud/aliyun/waf_v2_domains.go
  pkg/multicloud/aws/waf.go
  pkg/multicloud/azure/waf.go
  pkg/multicloud/qcloud/waf.go
Labels: size/L

#960 Automated cherry pick of #958: fix(qcloud): add waf upstream info
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/waf.go
  pkg/multicloud/aliyun/waf_domain.go
  pkg/multicloud/aliyun/waf_v2_domains.go
  pkg/multicloud/aws/waf.go
  pkg/multicloud/azure/waf.go
  pkg/multicloud/qcloud/waf.go
Labels: size/L

#964 fix(region): force account read only
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/oracle/provider/provider.go
Labels: size/S

#965 Automated cherry pick of #964: fix(region): force account read only
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/oracle/provider/provider.go
Labels: size/S

#966 Automated cherry pick of #964: fix(region): force account read only
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/oracle/provider/provider.go
Labels: size/S

#961 fix(esxi): avoid concurrent map read and map write
  pkg/multicloud/esxi/datacenter.go
Labels: size/XS

#962 Automated cherry pick of #961: fix(esxi): avoid concurrent map read and map write
  pkg/multicloud/esxi/datacenter.go
Labels: size/XS

#963 Automated cherry pick of #961: fix(esxi): avoid concurrent map read and map write
  pkg/multicloud/esxi/datacenter.go
Labels: size/XS

#967 fix(azure): web app ip addr
  pkg/multicloud/azure/web_app.go
Labels: size/M

#968 Automated cherry pick of #967: fix(azure): web app ip addr
  pkg/multicloud/azure/web_app.go
Labels: size/M

#969 Automated cherry pick of #967: fix(azure): web app ip addr
  pkg/multicloud/azure/web_app.go
Labels: size/M

#973 Automated cherry pick of #971: fix(oracle): oracle storage should be emulated
  pkg/multicloud/oracle/storage.go
Labels: size/XS

#972 Automated cherry pick of #971: fix(oracle): oracle storage should be emulated
  pkg/multicloud/oracle/storage.go
Labels: size/XS

#971 fix(oracle): oracle storage should be emulated
  pkg/multicloud/oracle/storage.go
Labels: size/XS
