Repository yunionio/cloudmux, pull requests merged in 2024-04, with the labels that each got.

#853 fix: provider prefix
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/proxmox/proxmox.go
  pkg/multicloud/remotefile/region.go
  pkg/multicloud/remotefile/remotefile.go
Labels: size/S

#854 Automated cherry pick of #853: fix: provider prefix
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/proxmox/proxmox.go
  pkg/multicloud/remotefile/region.go
  pkg/multicloud/remotefile/remotefile.go
Labels: size/S

#857 fix(aws): aws instance image info
  pkg/multicloud/aws/image.go
Labels: size/XS

#858 Automated cherry pick of #857: fix(aws): aws instance image info
  pkg/multicloud/aws/image.go
Labels: size/XS

#856 fix(qcloud): remove cache from qcloud
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/network.go
  pkg/multicloud/qcloud/shell/vpc.go
  pkg/multicloud/qcloud/vpc.go
  pkg/multicloud/qcloud/wire.go
  pkg/multicloud/qcloud/zone.go
Labels: size/XL

#859 fix(aws): optimized aws rule create
  pkg/multicloud/aws/securitygroup.go
Labels: size/S

#860 Automated cherry pick of #859: fix(aws): optimized aws rule create
  pkg/multicloud/aws/securitygroup.go
Labels: size/S

#861 Automated cherry pick of #859: fix(aws): optimized aws rule create
  pkg/multicloud/aws/securitygroup.go
Labels: size/S

#786 feat(ksyun): support ecs list
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/group.go
  pkg/multicloud/ksyun/host.go
  pkg/multicloud/ksyun/instancenic.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/policy.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/secgroup_rules.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/disks.go
  pkg/multicloud/ksyun/shell/eip.go
  pkg/multicloud/ksyun/shell/instances.go
  pkg/multicloud/ksyun/shell/network.go
  pkg/multicloud/ksyun/shell/securitygroup.go
  pkg/multicloud/ksyun/shell/storage.go
  pkg/multicloud/ksyun/shell/vpc.go
  pkg/multicloud/ksyun/shell/zone.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/tag_base.go
  pkg/multicloud/ksyun/user.go
  pkg/multicloud/ksyun/vpc.go
  pkg/multicloud/ksyun/wire.go
  pkg/multicloud/ksyun/zone.go
Labels: size/XXL

#862 Automated cherry pick of #786: feat(ksyun): support ecs list
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/group.go
  pkg/multicloud/ksyun/host.go
  pkg/multicloud/ksyun/instancenic.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/policy.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/secgroup_rules.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/disks.go
  pkg/multicloud/ksyun/shell/eip.go
  pkg/multicloud/ksyun/shell/instances.go
  pkg/multicloud/ksyun/shell/network.go
  pkg/multicloud/ksyun/shell/securitygroup.go
  pkg/multicloud/ksyun/shell/storage.go
  pkg/multicloud/ksyun/shell/vpc.go
  pkg/multicloud/ksyun/shell/zone.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/tag_base.go
  pkg/multicloud/ksyun/user.go
  pkg/multicloud/ksyun/vpc.go
  pkg/multicloud/ksyun/wire.go
  pkg/multicloud/ksyun/zone.go
Labels: size/XXL

#863 Automated cherry pick of #786: feat(ksyun): support ecs list
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/group.go
  pkg/multicloud/ksyun/host.go
  pkg/multicloud/ksyun/instancenic.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/policy.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/secgroup_rules.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/disks.go
  pkg/multicloud/ksyun/shell/eip.go
  pkg/multicloud/ksyun/shell/instances.go
  pkg/multicloud/ksyun/shell/network.go
  pkg/multicloud/ksyun/shell/securitygroup.go
  pkg/multicloud/ksyun/shell/storage.go
  pkg/multicloud/ksyun/shell/vpc.go
  pkg/multicloud/ksyun/shell/zone.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/tag_base.go
  pkg/multicloud/ksyun/user.go
  pkg/multicloud/ksyun/vpc.go
  pkg/multicloud/ksyun/wire.go
  pkg/multicloud/ksyun/zone.go
Labels: size/XXL

#864 fix(aws): image description
  pkg/multicloud/aws/image.go
Labels: size/XS

#865 Automated cherry pick of #864: fix(aws): image description
  pkg/multicloud/aws/image.go
Labels: size/XS

#866 Automated cherry pick of #864: fix(aws): image description
  pkg/multicloud/aws/image.go
Labels: size/XS

#867 fix(ksyun): GetIStorages addr err
  pkg/multicloud/ksyun/zone.go
Labels: size/XS

#868 Automated cherry pick of #867: fix(ksyun): GetIStorages addr err
  pkg/multicloud/ksyun/zone.go
Labels: size/XS

#869 Automated cherry pick of #867: fix(ksyun): GetIStorages addr err
  pkg/multicloud/ksyun/zone.go
Labels: size/XS

#870 fix: return region error
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/baidu/provider/provider.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/cephfs/provider/provider.go
  pkg/multicloud/cmx/shell/cloudprovider.go
  pkg/multicloud/cmx/shell/cmd.go
  pkg/multicloud/cmx/shell/helper.go
  pkg/multicloud/cmx/shell/region.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/cucloud/provider/provider.go
  pkg/multicloud/ecloud/client.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/ecloud/shell/region.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/jdcloud/jdcloud.go
  pkg/multicloud/jdcloud/jdcloudcli/main.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/proxmox/provider/provider.go
  pkg/multicloud/proxmox/proxmox.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qingcloud/provider/provider.go
  pkg/multicloud/remotefile/provider/provider.go
  pkg/multicloud/remotefile/remotefile.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/volcengine/provider/provider.go
  pkg/multicloud/volcengine/volcengine.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L

#871 Automated cherry pick of #870: fix: return region error
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/baidu/provider/provider.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/cephfs/provider/provider.go
  pkg/multicloud/cmx/shell/cloudprovider.go
  pkg/multicloud/cmx/shell/cmd.go
  pkg/multicloud/cmx/shell/helper.go
  pkg/multicloud/cmx/shell/region.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/cucloud/provider/provider.go
  pkg/multicloud/ecloud/client.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/ecloud/shell/region.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/jdcloud/jdcloud.go
  pkg/multicloud/jdcloud/jdcloudcli/main.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/proxmox/provider/provider.go
  pkg/multicloud/proxmox/proxmox.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qingcloud/provider/provider.go
  pkg/multicloud/remotefile/provider/provider.go
  pkg/multicloud/remotefile/remotefile.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/volcengine/provider/provider.go
  pkg/multicloud/volcengine/volcengine.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L

#872 Automated cherry pick of #870: fix: return region error
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/baidu/provider/provider.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/cmx/shell/cloudprovider.go
  pkg/multicloud/cmx/shell/cmd.go
  pkg/multicloud/cmx/shell/helper.go
  pkg/multicloud/cmx/shell/region.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/cucloud/provider/provider.go
  pkg/multicloud/ecloud/client.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/ecloud/shell/region.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/jdcloud/jdcloud.go
  pkg/multicloud/jdcloud/jdcloudcli/main.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/proxmox/provider/provider.go
  pkg/multicloud/proxmox/proxmox.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qingcloud/provider/provider.go
  pkg/multicloud/remotefile/provider/provider.go
  pkg/multicloud/remotefile/remotefile.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/volcengine/provider/provider.go
  pkg/multicloud/volcengine/volcengine.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L

#873 Automated cherry pick of #870: fix: return region error
  cmd/cmx/shell/cloudprovider.go
  cmd/cmx/shell/cmd.go
  cmd/cmx/shell/helper.go
  cmd/cmx/shell/region.go
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/cmx/shell/cloudprovider.go
  pkg/multicloud/cmx/shell/cmd.go
  pkg/multicloud/cmx/shell/helper.go
  pkg/multicloud/cmx/shell/region.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/ecloud/client.go
  pkg/multicloud/ecloud/provider/provider.go
  pkg/multicloud/ecloud/shell/region.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/jdcloud/jdcloud.go
  pkg/multicloud/jdcloud/jdcloudcli/main.go
  pkg/multicloud/jdcloud/provider/provider.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/proxmox/provider/provider.go
  pkg/multicloud/proxmox/proxmox.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/remotefile/provider/provider.go
  pkg/multicloud/remotefile/remotefile.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L

#874 Automated cherry pick of #856: fix(qcloud): remove cache from qcloud
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/network.go
  pkg/multicloud/qcloud/shell/vpc.go
  pkg/multicloud/qcloud/vpc.go
  pkg/multicloud/qcloud/wire.go
  pkg/multicloud/qcloud/zone.go
Labels: size/XL

#875 fix: avoid panic
  pkg/multicloud/apsara/vpc.go
Labels: size/XS

#876 Automated cherry pick of #875: fix: avoid panic
  pkg/multicloud/apsara/vpc.go
Labels: size/XS

#877 Automated cherry pick of #875: fix: avoid panic
  pkg/multicloud/apsara/vpc.go
Labels: size/XS

#878 Automated cherry pick of #875: fix: avoid panic
  pkg/multicloud/apsara/vpc.go
Labels: size/XS

#881 Automated cherry pick of #880: fix(vmware): esxi image dist
  pkg/multicloud/esxi/guestos.go
  pkg/multicloud/esxi/template.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/L

#883 fix(ksyun): instance list
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/project.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/project.go
  pkg/multicloud/ksyun/shell/tag.go
  pkg/multicloud/ksyun/tag.go
  pkg/multicloud/ksyun/vpc.go
Labels: size/L

#884 Automated cherry pick of #883: fix(ksyun): instance list
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/project.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/project.go
  pkg/multicloud/ksyun/shell/tag.go
  pkg/multicloud/ksyun/tag.go
  pkg/multicloud/ksyun/vpc.go
Labels: size/L

#885 Automated cherry pick of #883: fix(ksyun): instance list
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/project.go
  pkg/multicloud/ksyun/provider/provider.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/project.go
  pkg/multicloud/ksyun/shell/tag.go
  pkg/multicloud/ksyun/tag.go
  pkg/multicloud/ksyun/vpc.go
Labels: size/L

#886 fix(oracle): root account
  pkg/multicloud/oracle/disk.go
  pkg/multicloud/oracle/oracle.go
Labels: size/S

#887 Automated cherry pick of #886: fix(oracle): root account
  pkg/multicloud/oracle/disk.go
  pkg/multicloud/oracle/oracle.go
Labels: size/S

#890 Automated cherry pick of #889: fix(qcloud): vpc not found
  pkg/multicloud/qcloud/region.go
Labels: size/XS

#891 Automated cherry pick of #889: fix(qcloud): vpc not found
  pkg/multicloud/qcloud/region.go
Labels: size/XS

#892 fix(ksyun): sync ksyun networks
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/ksyun/wire.go
Labels: size/S

#893 Automated cherry pick of #892: fix(ksyun): sync ksyun networks
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/ksyun/wire.go
Labels: size/S

#894 Automated cherry pick of #892: fix(ksyun): sync ksyun networks
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/ksyun/wire.go
Labels: size/S

#896 fix(huawei): support delete prepaid resource
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/disk.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/elasticcache_instance.go
  pkg/multicloud/huawei/instance.go
Labels: size/M

#897 Automated cherry pick of #896: fix(huawei): support delete prepaid resource
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/disk.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/elasticcache_instance.go
  pkg/multicloud/huawei/instance.go
Labels: size/M

#899 fix(oracle): support monitor
  pkg/multicloud/oracle/boot-disk.go
  pkg/multicloud/oracle/disk.go
  pkg/multicloud/oracle/eip.go
  pkg/multicloud/oracle/instance.go
  pkg/multicloud/oracle/monitor.go
  pkg/multicloud/oracle/network.go
  pkg/multicloud/oracle/oracle.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/oracle/region.go
  pkg/multicloud/oracle/security-group.go
  pkg/multicloud/oracle/shell/monitor.go
Labels: size/L

#900 Automated cherry pick of #899: fix(oracle): support monitor
  pkg/multicloud/oracle/boot-disk.go
  pkg/multicloud/oracle/disk.go
  pkg/multicloud/oracle/eip.go
  pkg/multicloud/oracle/instance.go
  pkg/multicloud/oracle/monitor.go
  pkg/multicloud/oracle/network.go
  pkg/multicloud/oracle/oracle.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/oracle/region.go
  pkg/multicloud/oracle/security-group.go
  pkg/multicloud/oracle/shell/monitor.go
Labels: size/L

#901 Automated cherry pick of #899: fix(oracle): support monitor
  pkg/multicloud/oracle/boot-disk.go
  pkg/multicloud/oracle/disk.go
  pkg/multicloud/oracle/eip.go
  pkg/multicloud/oracle/instance.go
  pkg/multicloud/oracle/monitor.go
  pkg/multicloud/oracle/network.go
  pkg/multicloud/oracle/oracle.go
  pkg/multicloud/oracle/provider/provider.go
  pkg/multicloud/oracle/region.go
  pkg/multicloud/oracle/security-group.go
  pkg/multicloud/oracle/shell/monitor.go
Labels: size/L

#903 Automated cherry pick of #902: fix(oracle): avoid collect metric read only error
  pkg/multicloud/oracle/monitor.go
  pkg/multicloud/oracle/oracle.go
Labels: size/XS

#904 Automated cherry pick of #902: fix(oracle): avoid collect metric read only error
  pkg/multicloud/oracle/monitor.go
  pkg/multicloud/oracle/oracle.go
Labels: size/XS

#905 fix(ksyun): support get instance ExpiredTime
  pkg/multicloud/ksyun/instances.go
Labels: size/XS

#906 Automated cherry pick of #905: fix(ksyun): support get instance ExpiredTime
  pkg/multicloud/ksyun/instances.go
Labels: size/XS

#908 fix: api gen
  pkg/cloudprovider/cdn.go
Labels: size/XS

#909 Automated cherry pick of #908: fix: api gen
  pkg/cloudprovider/cdn.go
Labels: size/XS

#910 Automated cherry pick of #908: fix: api gen
  pkg/cloudprovider/cdn.go
Labels: size/XS

#911 Automated cherry pick of #908: fix: api gen
  pkg/cloudprovider/cdn.go
Labels: size/XS

#912 fix(project): sync provider project
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/apsara/project.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/google/google.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/project_base.go
Labels: size/M

#913 Automated cherry pick of #912: fix(project): sync provider project
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/apsara/project.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/google/google.go
  pkg/multicloud/nutanix/provider/provider.go
  pkg/multicloud/project_base.go
Labels: size/M

#914 fix: sync hostname
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/nutanix/instance.go
  pkg/multicloud/oracle/instance.go
  pkg/multicloud/proxmox/instance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/instance.go
Labels: size/S

#915 Automated cherry pick of #914: fix: sync hostname
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/nutanix/instance.go
  pkg/multicloud/oracle/instance.go
  pkg/multicloud/proxmox/instance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/instance.go
Labels: size/S

#917 fix: update hostname
  pkg/cloudprovider/instance.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/huawei/instance.go
Labels: size/S

#918 Automated cherry pick of #917: fix: update hostname
  pkg/cloudprovider/instance.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/huawei/instance.go
Labels: size/S

#919 Automated cherry pick of #917: fix: update hostname
  pkg/cloudprovider/instance.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/huawei/instance.go
Labels: size/S
