Repository yunionio/cloudmux, pull requests merged in 2024-12, with the labels that each got.

#1130 fix: update vendor 20241204
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#1131 Automated cherry pick of #1130: fix: update vendor 20241204
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#1132 fix(qcloud): cred balance
  pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#1133 Automated cherry pick of #1132: fix(qcloud): cred balance
  pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#1134 Automated cherry pick of #1132: fix(qcloud): cred balance
  pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#1135 fix(ksyun): vm status
  pkg/multicloud/ksyun/instances.go
Labels: size/XS

#1136 Automated cherry pick of #1135: fix(ksyun): vm status
  pkg/multicloud/ksyun/instances.go
Labels: size/XS

#1137 Automated cherry pick of #1135: fix(ksyun): vm status
  pkg/multicloud/ksyun/instances.go
Labels: size/XS

#1139 fix: update vendor v3.11.9 20241220
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS

#1142 Automated cherry pick of #1140: fix: ignore put object acl error
  go.mod
  go.sum
  pkg/multicloud/objectstore/buckets.go
  pkg/multicloud/objectstore/shell.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/s3cli/api-s3-datatypes.go
Labels: size/L

#1141 Automated cherry pick of #1140: fix: ignore put object acl error
  go.mod
  go.sum
  pkg/multicloud/objectstore/buckets.go
  pkg/multicloud/objectstore/shell.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/s3cli/api-s3-datatypes.go
Labels: size/L

#1140 fix: ignore put object acl error
  go.mod
  go.sum
  pkg/multicloud/objectstore/buckets.go
  pkg/multicloud/objectstore/shell.go
  vendor/modules.txt
  vendor/yunion.io/x/s3cli/api-s3-datatypes.go
Labels: size/M

#1144 fix(qcloud): rds cpu option
  pkg/multicloud/qcloud/rds_mysql.go
Labels: size/XS

#1145 Automated cherry pick of #1144: fix(qcloud): rds cpu option
  pkg/multicloud/qcloud/rds_mysql.go
Labels: size/XS

#1146 Automated cherry pick of #1144: fix(qcloud): rds cpu option
  pkg/multicloud/qcloud/rds_mysql.go
Labels: size/XS

#1149 fix(volc): volcengine account id
  pkg/multicloud/volcengine/volcengine.go
Labels: size/XS

#1147 fix(zstack): zstack auth url error
  pkg/multicloud/zstack/zstack.go
Labels: size/XS

#1148 Automated cherry pick of #1147: fix(zstack): zstack auth url error
  pkg/multicloud/zstack/zstack.go
Labels: size/XS

#1150 Automated cherry pick of #1149: fix(volc): volcengine account id
  pkg/multicloud/volcengine/volcengine.go
Labels: size/XS

#1151 fix: s3 cli support set sign version
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/s3cli/main.go
Labels: size/M

#1153 Automated cherry pick of #1151: fix: s3 cli support set sign version
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/s3cli/main.go
Labels: size/M

#1152 Automated cherry pick of #1151: fix: s3 cli support set sign version
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/s3cli/main.go
Labels: size/M

#1154 fix s3 provider support sign algorithm version
  pkg/multicloud/objectstore/provider/provider.go
Labels: size/M

#1155 Automated cherry pick of #1154: fix s3 provider support sign algorithm version
  pkg/multicloud/objectstore/provider/provider.go
Labels: size/M

#1156 Automated cherry pick of #1154: fix s3 provider support sign algorithm version
  pkg/multicloud/objectstore/provider/provider.go
Labels: size/M
