Repository yunionio/cloudmux, pull requests merged in 2025-03, with the labels that each got.

#1194 feat(zstack): 更新监控指标获取方法并增加内存使用率指标- 在 SZStackProvider 中将 GetMetrics 方…
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/monitor.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/shell/monitor.go
Labels: size/M

#1195 fix(qcloud): waf instance id
  pkg/multicloud/qcloud/waf.go
Labels: size/XS

#1197 Automated cherry pick of #1195: fix(qcloud): waf instance id
  pkg/multicloud/qcloud/waf.go
Labels: size/XS

#1198 Automated cherry pick of #1194: feat(zstack): 更新监控指标获取方法并增加内存使用率指标- 在 SZStackProvider 中将 GetMetrics 方…
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/monitor.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/shell/monitor.go
Labels: size/M

#1199 Automated cherry pick of #1194: feat(zstack): 更新监控指标获取方法并增加内存使用率指标- 在 SZStackProvider 中将 GetMetrics 方…
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/monitor.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/shell/monitor.go
Labels: size/M

#1200 Revert "fix(qcloud): waf instance id"
  pkg/multicloud/qcloud/waf.go
Labels: size/XS

#1203 fix(qcloud): waf domain id
  pkg/multicloud/qcloud/waf.go
Labels: size/XS

#1204 Automated cherry pick of #1203: fix(qcloud): waf domain id
  pkg/multicloud/qcloud/waf.go
Labels: size/XS

#1205 Automated cherry pick of #1203: fix(qcloud): waf domain id
  pkg/multicloud/qcloud/waf.go
Labels: size/XS

#1206 fix(azure): add reservation list
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/reservation.go
  pkg/multicloud/azure/shell/reservation.go
Labels: size/L

#1207 Automated cherry pick of #1206: fix(azure): add reservation list
  pkg/multicloud/azure/azure_v2.go
  pkg/multicloud/azure/reservation.go
  pkg/multicloud/azure/shell/reservation.go
Labels: size/L

#1209 fix(azure): monitor metric
  pkg/multicloud/azure/monitor.go
Labels: size/XS

#1211 Automated cherry pick of #1209: fix(azure): monitor metric
  pkg/multicloud/azure/monitor.go
Labels: size/XS

#1215 fix: objectstore download with progresser
  go.mod
  go.sum
  pkg/cloudprovider/objectstore.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
  vendor/yunion.io/x/pkg/util/qemuimgfmt/fmt.go
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
  vendor/yunion.io/x/pkg/utils/tags.go
Labels: size/L

#1212 fix(region): enable user with more params
  pkg/cloudprovider/clouduser.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/ram_user.go
  pkg/multicloud/aliyun/shell/ram_user.go
  pkg/multicloud/aws/iam_user.go
  pkg/multicloud/aws/shell/iam_user.go
  pkg/multicloud/clouduser.go
  pkg/multicloud/huawei/clouduser.go
  pkg/multicloud/qcloud/cam_user.go
  pkg/multicloud/volcengine/user.go
Labels: size/L

#1213 Automated cherry pick of #1212: fix(region): enable user with more params
  pkg/cloudprovider/clouduser.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/ram_user.go
  pkg/multicloud/aliyun/shell/ram_user.go
  pkg/multicloud/aws/iam_user.go
  pkg/multicloud/aws/shell/iam_user.go
  pkg/multicloud/clouduser.go
  pkg/multicloud/huawei/clouduser.go
  pkg/multicloud/qcloud/cam_user.go
  pkg/multicloud/volcengine/user.go
Labels: size/L

#1214 Automated cherry pick of #1212: fix(region): enable user with more params
  pkg/cloudprovider/clouduser.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/ram_user.go
  pkg/multicloud/aliyun/shell/ram_user.go
  pkg/multicloud/aws/iam_user.go
  pkg/multicloud/aws/shell/iam_user.go
  pkg/multicloud/clouduser.go
  pkg/multicloud/huawei/clouduser.go
  pkg/multicloud/qcloud/cam_user.go
  pkg/multicloud/volcengine/user.go
Labels: size/L

#1219 fix: update vendor 20250325
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
  vendor/yunion.io/x/pkg/util/qemuimgfmt/fmt.go
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
  vendor/yunion.io/x/pkg/utils/tags.go
Labels: size/M

#1221 Automated cherry pick of #1219: fix: update vendor 20250325
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Labels: size/S

#1222 fix: use streampipe2 to stream
  pkg/cloudprovider/objectstore.go
Labels: size/XS
