Repository yunionio/cloudmux, pull requests merged in 2025-08, with the labels that each got.

#1443 fix: add opts for cdn custom hostname
  pkg/cloudprovider/cdn.go
Labels: size/XS

#1445 fix(aws): add aws mfa cli
  pkg/multicloud/aws/mfa.go
  pkg/multicloud/aws/shell/mfa.go
Labels: size/L

#1446 fix(qcloud): lb backend sync
  pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/S

#1447 Automated cherry pick of #1446: fix(qcloud): lb backend sync
  pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/S

#1450 fix(aws): lb listener rule
  pkg/multicloud/aws/loadbalancercert.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/shell/lb.go
Labels: size/L

#1452 Automated cherry pick of #1450: fix(aws): lb listener rule
  pkg/multicloud/aws/loadbalancercert.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/shell/lb.go
Labels: size/L

#1455 Automated cherry pick of #1453: fix(aliyun): lb listener rule
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
Labels: size/XS

#1459 Automated cherry pick of #1456: fix: miss out errors of multipart objects
  pkg/cloudprovider/objectstore.go
Labels: size/S
