Repository yunionio/cloudmux, pull requests merged in 2025-09, with the labels that each got.

#1466 Automated cherry pick of #1465: fix(aws): cluster rds sync
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/dbinstance_cluster.go
  pkg/multicloud/aws/shell/dbinstance.go
Labels: size/L

#1468 Automated cherry pick of #1467: fix(aws): add region name
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/google/latitude_and_longitude.go
Labels: size/M

#1469 Automated cherry pick of #1467: fix(aws): add region name
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/google/latitude_and_longitude.go
Labels: size/M

#1474 Automated cherry pick of #1473: fix(qcloud): sync qcloud storage type
  pkg/multicloud/qcloud/rds_mysql.go
Labels: size/XS

#1476 fix(aws): rds category
  pkg/multicloud/aws/dbinstance.go
Labels: size/S

#1480 Automated cherry pick of #1478: fix(gcp): rds engine version
  pkg/multicloud/google/dbinstance.go
Labels: size/M

#1484 fix(aliyun): es instance type
  pkg/multicloud/aliyun/elastic_search_instance_types.go
Labels: size/L

#1486 Automated cherry pick of #1484: fix(aliyun): es instance type
  pkg/multicloud/aliyun/elastic_search_instance_types.go
Labels: size/L

#1489 Automated cherry pick of #1487: fix(esxi): root image path
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#1492 Automated cherry pick of #1490: fix(aliyun): mongodb shared count
  pkg/multicloud/aliyun/mongodb.go
Labels: size/XS

#1493 fix(gcp): vm sync
  pkg/multicloud/google/region.go
Labels: size/S

#1495 Automated cherry pick of #1493: fix(gcp): vm sync
  pkg/multicloud/google/region.go
Labels: size/S

#1500 Automated cherry pick of #1498: fix(qcloud): add qcloud disk usage metric
  pkg/cloudprovider/metrics.go
  pkg/multicloud/qcloud/monitor.go
  pkg/multicloud/qcloud/shell/monitor.go
Labels: size/S

#1498 fix(qcloud): add qcloud disk usage metric
  pkg/cloudprovider/metric.md
  pkg/cloudprovider/metrics.go
  pkg/multicloud/qcloud/monitor.go
  pkg/multicloud/qcloud/shell/monitor.go
Labels: size/S

#1501 fix(aliyun): mongodb kind code sync
  pkg/multicloud/aliyun/mongodb.go
Labels: size/S

#1502 Automated cherry pick of #1501: fix(aliyun): mongodb kind code sync
  pkg/multicloud/aliyun/mongodb.go
Labels: size/S

#1503 fix: add host ipmi info sync
  pkg/cloudprovider/resources.go
  pkg/multicloud/host_base.go
Labels: size/XS

#1505 fix(gcp): delete vm with deletion protection
  pkg/multicloud/google/instance.go
  pkg/multicloud/google/shell/instance.go
Labels: size/S

#1507 Automated cherry pick of #1505: fix(gcp): delete vm with deletion protection
  pkg/multicloud/google/instance.go
  pkg/multicloud/google/shell/instance.go
Labels: size/S

#1508 fix(gcp): add gcp storage const
  pkg/apis/compute/storage_const.go
  pkg/multicloud/google/instance.go
Labels: size/S

#1509 Automated cherry pick of #1508: fix(gcp): add gcp storage const
  pkg/apis/compute/storage_const.go
  pkg/multicloud/google/instance.go
Labels: size/S

#1510 Automated cherry pick of #1508: fix(gcp): add gcp storage const
  pkg/apis/compute/storage_const.go
  pkg/multicloud/google/instance.go
Labels: size/S

#1512 Automated cherry pick of #1511: fix(gcp): add pd extreme storage
  pkg/apis/compute/storage_const.go
  pkg/multicloud/google/instance.go
Labels: size/XS

#1513 Automated cherry pick of #1511: fix(gcp): add pd extreme storage
  pkg/apis/compute/storage_const.go
  pkg/multicloud/google/instance.go
Labels: size/XS

#1515 Automated cherry pick of #1514: fix(aws): master account id
  pkg/multicloud/aws/organizations.go
Labels: size/XS

#1523 fix(aws): rds endpoint
  pkg/multicloud/aws/dbinstance_cluster.go
Labels: size/XS

#1524 Automated cherry pick of #1523: fix(aws): rds endpoint
  pkg/multicloud/aws/dbinstance_cluster.go
Labels: size/XS

#1526 Automated cherry pick of #1525: fix(aws): rds cluster snapshot
  pkg/multicloud/aws/dbinstance_cluster.go
  pkg/multicloud/aws/dbinstance_cluster_snapshots.go
  pkg/multicloud/aws/dbinstance_snapshot.go
  pkg/multicloud/aws/shell/dbinstance.go
Labels: size/L

#1528 fix(gcp): vm create net params
  pkg/multicloud/google/instance.go
Labels: size/XS

#1530 Automated cherry pick of #1528: fix(gcp): vm create net params
  pkg/multicloud/google/instance.go
Labels: size/XS

#1527 fix(qcloud): sql server
  pkg/multicloud/qcloud/dbinstance.go
  pkg/multicloud/qcloud/rds_sqlserver.go
  pkg/multicloud/qcloud/shell/rds_sqlserver.go
  pkg/multicloud/qcloud/tag_base.go
Labels: size/XL

#1531 Automated cherry pick of #1527: fix(qcloud): sql server
  pkg/multicloud/qcloud/dbinstance.go
  pkg/multicloud/qcloud/rds_sqlserver.go
  pkg/multicloud/qcloud/shell/rds_sqlserver.go
  pkg/multicloud/qcloud/tag_base.go
Labels: size/XL

#1532 Automated cherry pick of #1527: fix(qcloud): sql server
  pkg/multicloud/qcloud/dbinstance.go
  pkg/multicloud/qcloud/rds_sqlserver.go
  pkg/multicloud/qcloud/shell/rds_sqlserver.go
  pkg/multicloud/qcloud/tag_base.go
Labels: size/XL

#1533 fix(qcloud): add sql server monitor
  pkg/multicloud/qcloud/monitor.go
Labels: size/M

#1535 Automated cherry pick of #1533: fix(qcloud): add sql server monitor
  pkg/multicloud/qcloud/monitor.go
Labels: size/M

#1537 Automated cherry pick of #1536: fix(qcloud): sub account sync
  pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#1540 Automated cherry pick of #1538: fix(qcloud): sync sqlserver expired time
  pkg/multicloud/qcloud/rds_sqlserver.go
Labels: size/XS

#1542 Automated cherry pick of #1541: fix(s3): add set bucket lifecycle
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#1543 Automated cherry pick of #1541: fix(s3): add set bucket lifecycle
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#1548 fix(aliyun): bucket sync
  pkg/multicloud/aliyun/aliyun.go
Labels: size/M

#1549 Automated cherry pick of #1548: fix(aliyun): bucket sync
  pkg/multicloud/aliyun/aliyun.go
Labels: size/M

#1553 Automated cherry pick of #1552: fix: support cnware
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/storage_const.go
Labels: size/S

#1558 Automated cherry pick of #1557: fix(huawei): bucket policy principal
  pkg/multicloud/huawei/bucket.go
Labels: size/XS

#1559 Automated cherry pick of #1557: fix(huawei): bucket policy principal
  pkg/multicloud/huawei/bucket.go
Labels: size/XS

#1560 Automated cherry pick of #1557: fix(huawei): bucket policy principal
  pkg/multicloud/huawei/bucket.go
Labels: size/XS

#1564 fix(ksyun): keypair import
  pkg/multicloud/ksyun/host.go
  pkg/multicloud/ksyun/keypair.go
  pkg/multicloud/ksyun/ksyun.go
Labels: size/S

#1566 Automated cherry pick of #1564: fix(ksyun): keypair import
  pkg/multicloud/ksyun/host.go
  pkg/multicloud/ksyun/keypair.go
  pkg/multicloud/ksyun/ksyun.go
Labels: size/S

#1568 Automated cherry pick of #1567: fix(ksyun): vm vnc
  pkg/cloudprovider/instance.go
  pkg/multicloud/ksyun/instances.go
Labels: size/M

#1569 Automated cherry pick of #1567: fix(ksyun): vm vnc
  pkg/cloudprovider/instance.go
  pkg/multicloud/ksyun/instances.go
Labels: size/M

#1570 fix(qcloud): event lookup readonly
  pkg/multicloud/qcloud/qcloud.go
Labels: size/XS

#1573 fix(ksyun): support post signv4
  pkg/apis/compute/storage_const.go
  pkg/cloudprovider/instance.go
  pkg/multicloud/ksyun/dbinstance.go
  pkg/multicloud/ksyun/dbinstance_account.go
  pkg/multicloud/ksyun/dbinstance_backup.go
  pkg/multicloud/ksyun/dbinstance_database.go
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/group.go
  pkg/multicloud/ksyun/host.go
  pkg/multicloud/ksyun/image.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/instancetype.go
  pkg/multicloud/ksyun/keypair.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/monitor.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/policy.go
  pkg/multicloud/ksyun/project.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/secgroup_rules.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/monitor.go
  pkg/multicloud/ksyun/snapshot.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/tag.go
  pkg/multicloud/ksyun/user.go
  pkg/multicloud/ksyun/vpc.go
  pkg/multicloud/ksyun/zone.go
Labels: size/XL

#1574 Automated cherry pick of #1573: fix(ksyun): support post signv4
  pkg/apis/compute/storage_const.go
  pkg/cloudprovider/instance.go
  pkg/multicloud/ksyun/dbinstance.go
  pkg/multicloud/ksyun/dbinstance_account.go
  pkg/multicloud/ksyun/dbinstance_backup.go
  pkg/multicloud/ksyun/dbinstance_database.go
  pkg/multicloud/ksyun/disks.go
  pkg/multicloud/ksyun/eip.go
  pkg/multicloud/ksyun/group.go
  pkg/multicloud/ksyun/host.go
  pkg/multicloud/ksyun/image.go
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/instancetype.go
  pkg/multicloud/ksyun/keypair.go
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/monitor.go
  pkg/multicloud/ksyun/network.go
  pkg/multicloud/ksyun/policy.go
  pkg/multicloud/ksyun/project.go
  pkg/multicloud/ksyun/region.go
  pkg/multicloud/ksyun/secgroup_rules.go
  pkg/multicloud/ksyun/securitygroup.go
  pkg/multicloud/ksyun/shell/monitor.go
  pkg/multicloud/ksyun/snapshot.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/tag.go
  pkg/multicloud/ksyun/user.go
  pkg/multicloud/ksyun/vpc.go
  pkg/multicloud/ksyun/zone.go
Labels: size/XL

#1576 Automated cherry pick of #1561: fix(ksyun): add auto pl storage type
  pkg/apis/compute/storage_const.go
  pkg/multicloud/ksyun/instancetype.go
  pkg/multicloud/ksyun/shell/instancetype.go
  pkg/multicloud/ksyun/storages.go
Labels: size/L

#1581 Automated cherry pick of #1580: fix(qcloud): metric period 60s
  pkg/multicloud/qcloud/monitor.go
Labels: size/XS

#1582 Automated cherry pick of #1580: fix(qcloud): metric period 60s
  pkg/multicloud/qcloud/monitor.go
Labels: size/XS

#1583 Automated cherry pick of #1580: fix(qcloud): metric period 60s
  pkg/multicloud/qcloud/monitor.go
Labels: size/XS

#1584 fix(ksyun): metric data
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/monitor.go
Labels: size/L

#1585 Automated cherry pick of #1584: fix(ksyun): metric data
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/monitor.go
Labels: size/L

#1586 Automated cherry pick of #1584: fix(ksyun): metric data
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/monitor.go
Labels: size/L

#1587 Automated cherry pick of #1584: fix(ksyun): metric data
  pkg/multicloud/ksyun/ksyun.go
  pkg/multicloud/ksyun/monitor.go
Labels: size/L

#1588 fix(ksyun): snapshot sync
  pkg/multicloud/ksyun/snapshot.go
Labels: size/XS

#1592 fix(ksyun): storage sync
  pkg/multicloud/ksyun/shell/disks.go
  pkg/multicloud/ksyun/shell/storage.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/zone.go
Labels: size/M

#1593 Automated cherry pick of #1592: fix(ksyun): storage sync
  pkg/multicloud/ksyun/shell/disks.go
  pkg/multicloud/ksyun/shell/storage.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/zone.go
Labels: size/M

#1594 Automated cherry pick of #1592: fix(ksyun): storage sync
  pkg/multicloud/ksyun/shell/disks.go
  pkg/multicloud/ksyun/shell/storage.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/zone.go
Labels: size/M

#1595 Automated cherry pick of #1592: fix(ksyun): storage sync
  pkg/multicloud/ksyun/shell/disks.go
  pkg/multicloud/ksyun/shell/storage.go
  pkg/multicloud/ksyun/storages.go
  pkg/multicloud/ksyun/zone.go
Labels: size/M
