Repository yunionio/cloudmux, pull requests merged in 2025-01, with the labels that each got.

#1157 fix(volc): region name
  pkg/multicloud/volcengine/region.go
Labels: size/M

#1158 Automated cherry pick of #1157: fix(volc): region name
  pkg/multicloud/volcengine/region.go
Labels: size/M

#1160 Automated cherry pick of #1159: fix(ksyun): vm filter
  pkg/multicloud/ksyun/instances.go
  pkg/multicloud/ksyun/region.go
Labels: size/M

#1161 fix(volc): region name
  pkg/multicloud/volcengine/region.go
Labels: size/XS

#1163 fix(volc): region name
  pkg/multicloud/volcengine/region.go
Labels: size/XS

#1168 fix: download/upload/copy large objects in parallel
  pkg/cloudprovider/objectstore.go
  pkg/multicloud/objectstore/shell.go
Labels: size/L

#1169 fix: download/upload/copy large objects in parallel
  pkg/cloudprovider/objectstore.go
  pkg/multicloud/objectstore/shell.go
Labels: size/L

#1170 fix: ignore upload multipart offset
  pkg/cloudprovider/objectstore.go
Labels: size/M
